// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agentruns.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishAgentRun = `-- name: FinishAgentRun :execrows
UPDATE agent_runs
SET status = $3, error = $4, turns = $5, ended_at = $6
WHERE id = $1 AND identity_id = $2
`

type FinishAgentRunParams struct {
	ID         pgtype.UUID
	IdentityID string
	Status     string
	Error      string
	Turns      int32
	EndedAt    pgtype.Timestamptz
}

func (q *Queries) FinishAgentRun(ctx context.Context, arg FinishAgentRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAgentRun,
		arg.ID,
		arg.IdentityID,
		arg.Status,
		arg.Error,
		arg.Turns,
		arg.EndedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentRun = `-- name: GetAgentRun :one
SELECT id, identity_id, session_id, agent, prompt_name, prompt_version,
       status, turns, started_at, ended_at, error
FROM agent_runs
WHERE id = $1 AND identity_id = $2
`

type GetAgentRunParams struct {
	ID         pgtype.UUID
	IdentityID string
}

func (q *Queries) GetAgentRun(ctx context.Context, arg GetAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRun, arg.ID, arg.IdentityID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SessionID,
		&i.Agent,
		&i.PromptName,
		&i.PromptVersion,
		&i.Status,
		&i.Turns,
		&i.StartedAt,
		&i.EndedAt,
		&i.Error,
	)
	return i, err
}

const insertAgentRun = `-- name: InsertAgentRun :exec
INSERT INTO agent_runs (
    id, identity_id, session_id, agent, prompt_name, prompt_version,
    status, turns, started_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAgentRunParams struct {
	ID            pgtype.UUID
	IdentityID    string
	SessionID     pgtype.UUID
	Agent         string
	PromptName    string
	PromptVersion string
	Status        string
	Turns         int32
	StartedAt     pgtype.Timestamptz
}

func (q *Queries) InsertAgentRun(ctx context.Context, arg InsertAgentRunParams) error {
	_, err := q.db.Exec(ctx, insertAgentRun,
		arg.ID,
		arg.IdentityID,
		arg.SessionID,
		arg.Agent,
		arg.PromptName,
		arg.PromptVersion,
		arg.Status,
		arg.Turns,
		arg.StartedAt,
	)
	return err
}

const insertToolCall = `-- name: InsertToolCall :execrows
INSERT INTO tool_calls (id, agent_run_id, tool_name, arguments, result, is_error, duration_ms, created_at)
SELECT $1, ar.id, $2, $3, $4, $5, $6, $7
FROM agent_runs ar
WHERE ar.id = $8 AND ar.identity_id = $9
`

type InsertToolCallParams struct {
	ID         pgtype.UUID
	ToolName   string
	Arguments  string
	Result     string
	IsError    bool
	DurationMs int32
	CreatedAt  pgtype.Timestamptz
	ID_2       pgtype.UUID
	IdentityID string
}

// Identity-scoped via a join back to agent_runs rather than a plain
// INSERT: a c.AgentRunID that doesn't exist, or belongs to a different
// identity, must insert nothing, and RowsAffected()==0 is how the
// adapter tells that apart from success.
func (q *Queries) InsertToolCall(ctx context.Context, arg InsertToolCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertToolCall,
		arg.ID,
		arg.ToolName,
		arg.Arguments,
		arg.Result,
		arg.IsError,
		arg.DurationMs,
		arg.CreatedAt,
		arg.ID_2,
		arg.IdentityID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAgentRuns = `-- name: ListAgentRuns :many
SELECT id, identity_id, session_id, agent, prompt_name, prompt_version,
       status, turns, started_at, ended_at, error
FROM agent_runs
WHERE identity_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListAgentRunsParams struct {
	IdentityID string
	Limit      int32
}

func (q *Queries) ListAgentRuns(ctx context.Context, arg ListAgentRunsParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listAgentRuns, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SessionID,
			&i.Agent,
			&i.PromptName,
			&i.PromptVersion,
			&i.Status,
			&i.Turns,
			&i.StartedAt,
			&i.EndedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsForRun = `-- name: ListToolCallsForRun :many
SELECT id, agent_run_id, tool_name, arguments, result, is_error, duration_ms, created_at
FROM tool_calls
WHERE agent_run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListToolCallsForRun(ctx context.Context, agentRunID pgtype.UUID) ([]ToolCall, error) {
	rows, err := q.db.Query(ctx, listToolCallsForRun, agentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolCall
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.AgentRunID,
			&i.ToolName,
			&i.Arguments,
			&i.Result,
			&i.IsError,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
