// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agentruns.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishAgentRun = `-- name: FinishAgentRun :execrows
UPDATE agent_runs
SET status = $3, error = $4, output = $5, turns = $6, ended_at = $7
WHERE id = $1 AND identity_id = $2
`

type FinishAgentRunParams struct {
	ID         pgtype.UUID
	IdentityID string
	Status     string
	Error      string
	Output     string
	Turns      int32
	EndedAt    pgtype.Timestamptz
}

func (q *Queries) FinishAgentRun(ctx context.Context, arg FinishAgentRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishAgentRun,
		arg.ID,
		arg.IdentityID,
		arg.Status,
		arg.Error,
		arg.Output,
		arg.Turns,
		arg.EndedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentRun = `-- name: GetAgentRun :one
SELECT id, identity_id, session_id, agent, prompt_name, prompt_version,
       status, turns, started_at, ended_at, error, system, input, output,
       parent_run_id
FROM agent_runs
WHERE agent_runs.id = $1 AND agent_runs.identity_id = $2
  AND (agent_runs.session_id IS NULL
       OR EXISTS (SELECT 1 FROM sessions s WHERE s.id = agent_runs.session_id AND s.deleted_at IS NULL))
`

type GetAgentRunParams struct {
	ID         pgtype.UUID
	IdentityID string
}

// Same filter as ListAgentRuns above, and the reason the two child
// queries below need none of their own: /ai/agents/{id} resolves the
// run through this query first, so a deleted session's trace 404s
// before its tool calls or turns are ever fetched.
func (q *Queries) GetAgentRun(ctx context.Context, arg GetAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRun, arg.ID, arg.IdentityID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SessionID,
		&i.Agent,
		&i.PromptName,
		&i.PromptVersion,
		&i.Status,
		&i.Turns,
		&i.StartedAt,
		&i.EndedAt,
		&i.Error,
		&i.System,
		&i.Input,
		&i.Output,
		&i.ParentRunID,
	)
	return i, err
}

const insertAgentRun = `-- name: InsertAgentRun :exec
INSERT INTO agent_runs (
    id, identity_id, session_id, agent, prompt_name, prompt_version,
    status, turns, started_at, system, input, parent_run_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertAgentRunParams struct {
	ID            pgtype.UUID
	IdentityID    string
	SessionID     pgtype.UUID
	Agent         string
	PromptName    string
	PromptVersion string
	Status        string
	Turns         int32
	StartedAt     pgtype.Timestamptz
	System        string
	Input         string
	ParentRunID   pgtype.UUID
}

func (q *Queries) InsertAgentRun(ctx context.Context, arg InsertAgentRunParams) error {
	_, err := q.db.Exec(ctx, insertAgentRun,
		arg.ID,
		arg.IdentityID,
		arg.SessionID,
		arg.Agent,
		arg.PromptName,
		arg.PromptVersion,
		arg.Status,
		arg.Turns,
		arg.StartedAt,
		arg.System,
		arg.Input,
		arg.ParentRunID,
	)
	return err
}

const insertAgentTurn = `-- name: InsertAgentTurn :execrows
INSERT INTO agent_turns (id, agent_run_id, turn_number, text, created_at)
SELECT $1, ar.id, $2, $3, $4
FROM agent_runs ar
WHERE ar.id = $5 AND ar.identity_id = $6
`

type InsertAgentTurnParams struct {
	ID         pgtype.UUID
	TurnNumber int32
	Text       string
	CreatedAt  pgtype.Timestamptz
	ID_2       pgtype.UUID
	IdentityID string
}

// Identity-scoped via a join back to agent_runs, same convention as
// InsertToolCall above.
func (q *Queries) InsertAgentTurn(ctx context.Context, arg InsertAgentTurnParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAgentTurn,
		arg.ID,
		arg.TurnNumber,
		arg.Text,
		arg.CreatedAt,
		arg.ID_2,
		arg.IdentityID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertToolCall = `-- name: InsertToolCall :execrows
INSERT INTO tool_calls (id, agent_run_id, tool_name, arguments, result, is_error, duration_ms, created_at)
SELECT $1, ar.id, $2, $3, $4, $5, $6, $7
FROM agent_runs ar
WHERE ar.id = $8 AND ar.identity_id = $9
`

type InsertToolCallParams struct {
	ID         pgtype.UUID
	ToolName   string
	Arguments  string
	Result     string
	IsError    bool
	DurationMs int32
	CreatedAt  pgtype.Timestamptz
	ID_2       pgtype.UUID
	IdentityID string
}

// Identity-scoped via a join back to agent_runs rather than a plain
// INSERT: a c.AgentRunID that doesn't exist, or belongs to a different
// identity, must insert nothing, and RowsAffected()==0 is how the
// adapter tells that apart from success.
func (q *Queries) InsertToolCall(ctx context.Context, arg InsertToolCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertToolCall,
		arg.ID,
		arg.ToolName,
		arg.Arguments,
		arg.Result,
		arg.IsError,
		arg.DurationMs,
		arg.CreatedAt,
		arg.ID_2,
		arg.IdentityID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAgentRuns = `-- name: ListAgentRuns :many
SELECT id, identity_id, session_id, agent, prompt_name, prompt_version,
       status, turns, started_at, ended_at, error, system, input, output,
       parent_run_id
FROM agent_runs
WHERE agent_runs.identity_id = $1
  AND (agent_runs.session_id IS NULL
       OR EXISTS (SELECT 1 FROM sessions s WHERE s.id = agent_runs.session_id AND s.deleted_at IS NULL))
ORDER BY started_at DESC
LIMIT $2
`

type ListAgentRunsParams struct {
	IdentityID string
	Limit      int32
}

// Soft delete, session cascade (Phase 4 Task D) — see the header
// comment in db/queries/documents.sql for the shape.
//
// agent_runs looks like an operational record, and mostly is, but
// system/input/output hold the learner's own text VERBATIM: for a
// feedback run, input is the selection they asked to have reviewed
// (application/agentrun.Runner sets it from the first user message),
// and a get_recent_writing tool call's result carries up to 1000 runes
// of that session's document. /ai/agents renders all of it. Filtering
// an operational record felt unnecessary until you notice it is a
// second, unindexed copy of the writing.
//
// session_id is nullable (00018), and a NULL one belongs to no session
// — lesson generation, the weekly summary — so it must stay visible;
// that is what the "IS NULL OR" half says. No statistic reads
// agent_runs: AgentUsageStats is over ai_requests, so nothing on
// /learner moves.
func (q *Queries) ListAgentRuns(ctx context.Context, arg ListAgentRunsParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listAgentRuns, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SessionID,
			&i.Agent,
			&i.PromptName,
			&i.PromptVersion,
			&i.Status,
			&i.Turns,
			&i.StartedAt,
			&i.EndedAt,
			&i.Error,
			&i.System,
			&i.Input,
			&i.Output,
			&i.ParentRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTurnsForRun = `-- name: ListAgentTurnsForRun :many
SELECT id, agent_run_id, turn_number, text, created_at
FROM agent_turns
WHERE agent_run_id = $1
ORDER BY turn_number ASC
`

func (q *Queries) ListAgentTurnsForRun(ctx context.Context, agentRunID pgtype.UUID) ([]AgentTurn, error) {
	rows, err := q.db.Query(ctx, listAgentTurnsForRun, agentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTurn
	for rows.Next() {
		var i AgentTurn
		if err := rows.Scan(
			&i.ID,
			&i.AgentRunID,
			&i.TurnNumber,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsForRun = `-- name: ListToolCallsForRun :many
SELECT id, agent_run_id, tool_name, arguments, result, is_error, duration_ms, created_at
FROM tool_calls
WHERE agent_run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListToolCallsForRun(ctx context.Context, agentRunID pgtype.UUID) ([]ToolCall, error) {
	rows, err := q.db.Query(ctx, listToolCallsForRun, agentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolCall
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.AgentRunID,
			&i.ToolName,
			&i.Arguments,
			&i.Result,
			&i.IsError,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
