// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_requests.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAIRequest = `-- name: InsertAIRequest :exec
INSERT INTO ai_requests (
    id, identity_id, session_id, capability, provider, model,
    prompt_name, prompt_version, latency_ms, input_tokens, output_tokens,
    cost_usd, success, error, created_at, agent
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type InsertAIRequestParams struct {
	ID            pgtype.UUID
	IdentityID    string
	SessionID     pgtype.UUID
	Capability    string
	Provider      string
	Model         string
	PromptName    string
	PromptVersion string
	LatencyMs     int32
	InputTokens   int32
	OutputTokens  int32
	CostUsd       pgtype.Numeric
	Success       bool
	Error         string
	CreatedAt     pgtype.Timestamptz
	Agent         string
}

func (q *Queries) InsertAIRequest(ctx context.Context, arg InsertAIRequestParams) error {
	_, err := q.db.Exec(ctx, insertAIRequest,
		arg.ID,
		arg.IdentityID,
		arg.SessionID,
		arg.Capability,
		arg.Provider,
		arg.Model,
		arg.PromptName,
		arg.PromptVersion,
		arg.LatencyMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.Success,
		arg.Error,
		arg.CreatedAt,
		arg.Agent,
	)
	return err
}

const listAIRequests = `-- name: ListAIRequests :many
SELECT id, identity_id, session_id, capability, provider, model,
       prompt_name, prompt_version, latency_ms, input_tokens, output_tokens,
       cost_usd, success, error, created_at, agent
FROM ai_requests
WHERE identity_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAIRequestsParams struct {
	IdentityID string
	Limit      int32
}

func (q *Queries) ListAIRequests(ctx context.Context, arg ListAIRequestsParams) ([]AiRequest, error) {
	rows, err := q.db.Query(ctx, listAIRequests, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiRequest
	for rows.Next() {
		var i AiRequest
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SessionID,
			&i.Capability,
			&i.Provider,
			&i.Model,
			&i.PromptName,
			&i.PromptVersion,
			&i.LatencyMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.Success,
			&i.Error,
			&i.CreatedAt,
			&i.Agent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
