// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_ratings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ratingsForRequests = `-- name: RatingsForRequests :many
SELECT ai_request_id, rating
FROM ai_ratings
WHERE identity_id = $1 AND ai_request_id = ANY($2::uuid[])
`

type RatingsForRequestsParams struct {
	IdentityID string
	RequestIds []pgtype.UUID
}

type RatingsForRequestsRow struct {
	AiRequestID pgtype.UUID
	Rating      int32
}

// Scoped by identity_id first: a caller can never read another
// identity's rating of a request, even one it names explicitly.
func (q *Queries) RatingsForRequests(ctx context.Context, arg RatingsForRequestsParams) ([]RatingsForRequestsRow, error) {
	rows, err := q.db.Query(ctx, ratingsForRequests, arg.IdentityID, arg.RequestIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RatingsForRequestsRow
	for rows.Next() {
		var i RatingsForRequestsRow
		if err := rows.Scan(&i.AiRequestID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAIRating = `-- name: UpsertAIRating :execrows
INSERT INTO ai_ratings (id, ai_request_id, identity_id, rating, created_at)
SELECT $1, $2, $3, $4, $5
WHERE EXISTS (SELECT 1 FROM ai_requests req WHERE req.id = $2 AND req.identity_id = $3)
ON CONFLICT (ai_request_id, identity_id)
DO UPDATE SET rating = EXCLUDED.rating, created_at = EXCLUDED.created_at
`

type UpsertAIRatingParams struct {
	ID          pgtype.UUID
	AiRequestID pgtype.UUID
	IdentityID  string
	Rating      int32
	CreatedAt   pgtype.Timestamptz
}

// One rating per (ai_request_id, identity_id): rating the same request
// again replaces the previous value and timestamp rather than adding a
// second row, per the UNIQUE constraint in 00007_ai_ratings.sql. The id
// of an existing row is left untouched by the conflict.
//
// The WHERE EXISTS clause verifies ai_request_id actually belongs to
// identity_id before writing anything — the same "never trust the
// caller, check via a join" shape UpdateCorrectionStatus
// (feedback.sql) uses — so one identity can never attach a rating to
// another identity's AI request by guessing/observing its id.
// :execrows lets the caller tell "wrote" from "no such request for
// this identity" apart: zero rows affected means the latter.
func (q *Queries) UpsertAIRating(ctx context.Context, arg UpsertAIRatingParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertAIRating,
		arg.ID,
		arg.AiRequestID,
		arg.IdentityID,
		arg.Rating,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
