// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics_v2.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentUsageStats = `-- name: AgentUsageStats :many
SELECT agent,
       COUNT(*)::int AS requests,
       (COUNT(*) FILTER (WHERE success))::int AS successes,
       ROUND(AVG(latency_ms))::int AS avg_latency_ms
FROM ai_requests
WHERE identity_id = $1
GROUP BY agent
ORDER BY requests DESC, agent ASC
`

type AgentUsageStatsRow struct {
	Agent        string
	Requests     int32
	Successes    int32
	AvgLatencyMs int32
}

// Per-agent request volume, success count, and average latency from
// ai_requests — agent is ” for rows written before the column existed
// (see the 00017 migration); the ” bucket is returned like any other
// and it's the HTTP layer's job to label it for display (see
// learner.html.tmpl's 未分類 fallback). Raw counts only (see
// ConfidenceCalibration's doc comment above) — SuccessRate is derived
// in application/analytics.Service from Requests/Successes.
func (q *Queries) AgentUsageStats(ctx context.Context, identityID string) ([]AgentUsageStatsRow, error) {
	rows, err := q.db.Query(ctx, agentUsageStats, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentUsageStatsRow
	for rows.Next() {
		var i AgentUsageStatsRow
		if err := rows.Scan(
			&i.Agent,
			&i.Requests,
			&i.Successes,
			&i.AvgLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const confidenceCalibration = `-- name: ConfidenceCalibration :many
SELECT ea.confidence AS confidence,
       COUNT(*)::int AS attempts,
       (COUNT(*) FILTER (WHERE ea.correct))::int AS corrects
FROM exercise_attempts ea
JOIN exercises e ON e.id = ea.exercise_id
WHERE e.identity_id = $1 AND ea.confidence IS NOT NULL
GROUP BY ea.confidence
ORDER BY ea.confidence
`

type ConfidenceCalibrationRow struct {
	Confidence pgtype.Int4
	Attempts   int32
	Corrects   int32
}

// Per-confidence-level (1..5) attempt count and correct count, from
// exercise_attempts rows that actually carry a confidence value —
// confidence IS NULL rows (no self-rating given) never contribute.
// Raw counts only, per the codebase's "SQL returns raw data, Go
// derives" convention (see analytics.go's Statistics doc comment):
// application/analytics.Service computes CorrectRate from
// Attempts/Corrects, the same way it computes AcceptanceRate from
// Statistics' raw correction counts. An identity with no
// confidence-rated attempts at all simply gets zero rows back, which
// the template renders as an explicit empty state.
func (q *Queries) ConfidenceCalibration(ctx context.Context, identityID string) ([]ConfidenceCalibrationRow, error) {
	rows, err := q.db.Query(ctx, confidenceCalibration, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfidenceCalibrationRow
	for rows.Next() {
		var i ConfidenceCalibrationRow
		if err := rows.Scan(&i.Confidence, &i.Attempts, &i.Corrects); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAIRequestsForIdentity = `-- name: CountAIRequestsForIdentity :one
SELECT COUNT(*)::int FROM ai_requests WHERE identity_id = $1
`

func (q *Queries) CountAIRequestsForIdentity(ctx context.Context, identityID string) (int32, error) {
	row := q.db.QueryRow(ctx, countAIRequestsForIdentity, identityID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const learningEventsByType = `-- name: LearningEventsByType :many
SELECT type, COUNT(*)::int AS count
FROM learning_events
WHERE identity_id = $1
GROUP BY type
ORDER BY type
`

type LearningEventsByTypeRow struct {
	Type  string
	Count int32
}

func (q *Queries) LearningEventsByType(ctx context.Context, identityID string) ([]LearningEventsByTypeRow, error) {
	rows, err := q.db.Query(ctx, learningEventsByType, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningEventsByTypeRow
	for rows.Next() {
		var i LearningEventsByTypeRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const practiceStats = `-- name: PracticeStats :one
SELECT
    COUNT(*)::int AS answered,
    COUNT(*) FILTER (WHERE evidence->>'correct' = 'true')::int AS correct,
    COUNT(*) FILTER (WHERE COALESCE(evidence->>'subject_type', 'concept') = 'word')::int AS words,
    COUNT(*) FILTER (WHERE COALESCE(evidence->>'subject_type', 'concept') = 'concept')::int AS concepts
FROM learning_events
WHERE identity_id = $1 AND type = 'quiz.answered'
`

type PracticeStatsRow struct {
	Answered int32
	Correct  int32
	Words    int32
	Concepts int32
}

// 学習's 練習 section: how much drilling has actually happened, and how
// much of it went right, split by what was drilled.
//
// Read from learning_events rather than exercise_attempts because the
// event is what the rest of the learning loop reacts to — the retrieval
// scheduler and the learner model both consume quiz.answered — so a
// number derived from the same row is a number that agrees with the
// queue and the observations beside it on the page.
//
// subject_type is absent on events written before drills carried one;
// those were all concept drills, and are counted as such.
func (q *Queries) PracticeStats(ctx context.Context, identityID string) (PracticeStatsRow, error) {
	row := q.db.QueryRow(ctx, practiceStats, identityID)
	var i PracticeStatsRow
	err := row.Scan(
		&i.Answered,
		&i.Correct,
		&i.Words,
		&i.Concepts,
	)
	return i, err
}

const recentDrillAttempts = `-- name: RecentDrillAttempts :many
SELECT
    subject,
    COALESCE(evidence->>'subject_type', 'concept') AS subject_type,
    COALESCE(evidence->>'subject_ref', evidence->>'concept', '') AS subject_ref,
    COALESCE(evidence->>'type', '') AS exercise_type,
    (evidence->>'correct' = 'true') AS correct,
    occurred_at
FROM learning_events
WHERE identity_id = $1 AND type = 'quiz.answered'
ORDER BY occurred_at DESC
LIMIT $2
`

type RecentDrillAttemptsParams struct {
	IdentityID string
	LimitCount int32
}

type RecentDrillAttemptsRow struct {
	Subject      string
	SubjectType  interface{}
	SubjectRef   interface{}
	ExerciseType interface{}
	Correct      bool
	OccurredAt   pgtype.Timestamptz
}

// The last N drills a learner answered, newest first — what 練習's
// end-of-set summary is built from.
//
// learning_events, not exercise_attempts: the event is what the rest of
// the loop consumes (the scheduler and the learner model both read
// quiz.answered), so a summary derived from the same rows cannot
// disagree with the review queue it sends the learner back to.
func (q *Queries) RecentDrillAttempts(ctx context.Context, arg RecentDrillAttemptsParams) ([]RecentDrillAttemptsRow, error) {
	rows, err := q.db.Query(ctx, recentDrillAttempts, arg.IdentityID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentDrillAttemptsRow
	for rows.Next() {
		var i RecentDrillAttemptsRow
		if err := rows.Scan(
			&i.Subject,
			&i.SubjectType,
			&i.SubjectRef,
			&i.ExerciseType,
			&i.Correct,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subjectOccurrencesByWeek = `-- name: SubjectOccurrencesByWeek :many
SELECT date_trunc('week', occurred_at AT TIME ZONE 'UTC')::date AS week_start,
       COUNT(*)::int AS count
FROM learning_events
WHERE identity_id = $1
  AND occurred_at >= $2
  AND (
    ($3::text = 'concept' AND type = 'grammar.concept.encountered' AND subject = $4)
    OR ($3::text = 'correction-type' AND type = 'correction.presented' AND evidence ->> 'type' = $4)
  )
GROUP BY week_start
ORDER BY week_start
`

type SubjectOccurrencesByWeekParams struct {
	IdentityID string
	OccurredAt pgtype.Timestamptz
	Column3    string
	Subject    string
}

type SubjectOccurrencesByWeekRow struct {
	WeekStart pgtype.Date
	Count     int32
}

// Weekly occurrence counts for one (subject_type, subject) pair from
// $3/$4, over learning_events from $2 (inclusive) to now. Mirrors
// application/learnermodel's classify()/eventTypeFor() event-type
// mapping used for weakness detection:
//   - subject_type 'concept': occurrences are
//     grammar.concept.encountered events whose subject IS the concept
//     slug directly.
//   - subject_type 'correction-type': occurrences are
//     correction.presented events, but learning_events.subject holds
//     the CORRECTION ID for those (see learnermodel.dedupKey's doc
//     comment) — the correction type text instead lives in
//     evidence->>'type'.
//
// date_trunc runs against occurred_at converted to plain UTC (AT TIME
// ZONE 'UTC') rather than relying on the session's timezone setting,
// so week buckets are deterministic regardless of how the DB
// connection is configured — the Go caller computes its own zero-fill
// week boundaries the identical way (see isoWeekStarts).
func (q *Queries) SubjectOccurrencesByWeek(ctx context.Context, arg SubjectOccurrencesByWeekParams) ([]SubjectOccurrencesByWeekRow, error) {
	rows, err := q.db.Query(ctx, subjectOccurrencesByWeek,
		arg.IdentityID,
		arg.OccurredAt,
		arg.Column3,
		arg.Subject,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubjectOccurrencesByWeekRow
	for rows.Next() {
		var i SubjectOccurrencesByWeekRow
		if err := rows.Scan(&i.WeekStart, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topWeaknessSubjects = `-- name: TopWeaknessSubjects :many
SELECT subject, subject_type
FROM learner_observations
WHERE identity_id = $1 AND kind = 'weakness'
ORDER BY confidence DESC, updated_at DESC, subject ASC
LIMIT 3
`

type TopWeaknessSubjectsRow struct {
	Subject     string
	SubjectType string
}

// The (subject_type, subject) pairs WeaknessTrends charts: identity's
// top 3 live weaknesses (learner_observations.kind='weakness'), most
// confident first with recency as the tiebreak, subject ASC beneath
// that so ties are stable across requests (mirrors TopErrorTypes'
// tiebreak rationale in analytics.sql).
func (q *Queries) TopWeaknessSubjects(ctx context.Context, identityID string) ([]TopWeaknessSubjectsRow, error) {
	rows, err := q.db.Query(ctx, topWeaknessSubjects, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopWeaknessSubjectsRow
	for rows.Next() {
		var i TopWeaknessSubjectsRow
		if err := rows.Scan(&i.Subject, &i.SubjectType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vocabFunnel = `-- name: VocabFunnel :one
SELECT COALESCE(SUM(lookups), 0)::int AS looked_up,
       COALESCE(SUM(productions), 0)::int AS produced,
       COALESCE(SUM(successful_productions), 0)::int AS produced_correctly
FROM vocabulary_items
WHERE identity_id = $1
`

type VocabFunnelRow struct {
	LookedUp          int32
	Produced          int32
	ProducedCorrectly int32
}

// Raw sums across the identity's whole vocabulary bank: lookups,
// productions, and successful productions — the three stages of
// storage.VocabFunnel. COALESCE covers an identity with no vocabulary
// rows at all (SUM of zero rows is NULL, not 0).
func (q *Queries) VocabFunnel(ctx context.Context, identityID string) (VocabFunnelRow, error) {
	row := q.db.QueryRow(ctx, vocabFunnel, identityID)
	var i VocabFunnelRow
	err := row.Scan(&i.LookedUp, &i.Produced, &i.ProducedCorrectly)
	return i, err
}
