// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlcgen

import (
	"context"
)

const countCorrectionsByStatus = `-- name: CountCorrectionsByStatus :many
SELECT c.status, COUNT(*)::int AS count
FROM corrections c
JOIN feedback_requests f ON f.id = c.feedback_request_id
WHERE f.identity_id = $1
GROUP BY c.status
`

type CountCorrectionsByStatusRow struct {
	Status string
	Count  int32
}

// corrections has no identity_id of its own; scope through the owning
// feedback_requests row, same join every other identity-scoped
// corrections query in this codebase uses.
func (q *Queries) CountCorrectionsByStatus(ctx context.Context, identityID string) ([]CountCorrectionsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countCorrectionsByStatus, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountCorrectionsByStatusRow
	for rows.Next() {
		var i CountCorrectionsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFeedbackRequests = `-- name: CountFeedbackRequests :one
SELECT COUNT(*)::int FROM feedback_requests WHERE identity_id = $1
`

func (q *Queries) CountFeedbackRequests(ctx context.Context, identityID string) (int32, error) {
	row := q.db.QueryRow(ctx, countFeedbackRequests, identityID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRunesWritten = `-- name: CountRunesWritten :one
SELECT COALESCE(SUM(char_length(content)), 0)::int FROM documents WHERE identity_id = $1
`

// char_length counts Postgres code points, which matches Go's rune
// count for Japanese text (unlike octet_length/byte length).
func (q *Queries) CountRunesWritten(ctx context.Context, identityID string) (int32, error) {
	row := q.db.QueryRow(ctx, countRunesWritten, identityID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*)::int FROM sessions WHERE identity_id = $1
`

func (q *Queries) CountSessions(ctx context.Context, identityID string) (int32, error) {
	row := q.db.QueryRow(ctx, countSessions, identityID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const topErrorTypes = `-- name: TopErrorTypes :many
SELECT c.type, COUNT(*)::int AS count
FROM corrections c
JOIN feedback_requests f ON f.id = c.feedback_request_id
WHERE f.identity_id = $1
GROUP BY c.type
ORDER BY count(*) DESC, c.type ASC
LIMIT 5
`

type TopErrorTypesRow struct {
	Type  string
	Count int32
}

// Secondary "type ASC" tiebreak keeps the top-5 stable across requests
// when two error types are presented equally often — Postgres makes no
// ordering guarantee among GROUP BY ties otherwise.
func (q *Queries) TopErrorTypes(ctx context.Context, identityID string) ([]TopErrorTypesRow, error) {
	rows, err := q.db.Query(ctx, topErrorTypes, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopErrorTypesRow
	for rows.Next() {
		var i TopErrorTypesRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
