// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anki.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvedAnkiCardsForExport = `-- name: ApprovedAnkiCardsForExport :many
SELECT id, identity_id, source_type, source_id, front, back, notes, status, created_at
FROM anki_cards
WHERE identity_id = $1 AND status = 'approved'
ORDER BY created_at ASC
`

func (q *Queries) ApprovedAnkiCardsForExport(ctx context.Context, identityID string) ([]AnkiCard, error) {
	rows, err := q.db.Query(ctx, approvedAnkiCardsForExport, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnkiCard
	for rows.Next() {
		var i AnkiCard
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SourceType,
			&i.SourceID,
			&i.Front,
			&i.Back,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAnkiCard = `-- name: InsertAnkiCard :exec
INSERT INTO anki_cards (id, identity_id, source_type, source_id, front, back, notes, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAnkiCardParams struct {
	ID         pgtype.UUID
	IdentityID string
	SourceType string
	SourceID   string
	Front      string
	Back       string
	Notes      string
	Status     string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertAnkiCard(ctx context.Context, arg InsertAnkiCardParams) error {
	_, err := q.db.Exec(ctx, insertAnkiCard,
		arg.ID,
		arg.IdentityID,
		arg.SourceType,
		arg.SourceID,
		arg.Front,
		arg.Back,
		arg.Notes,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const listAnkiCards = `-- name: ListAnkiCards :many
SELECT id, identity_id, source_type, source_id, front, back, notes, status, created_at
FROM anki_cards
WHERE identity_id = $1
  AND ($2::text = '' OR status = $2)
ORDER BY created_at DESC
`

type ListAnkiCardsParams struct {
	IdentityID string
	Status     string
}

// status "" (sqlc.arg(status) = ”) means "every status" — mirrors
// ListVocabularyItems' own empty-string-means-unfiltered convention.
func (q *Queries) ListAnkiCards(ctx context.Context, arg ListAnkiCardsParams) ([]AnkiCard, error) {
	rows, err := q.db.Query(ctx, listAnkiCards, arg.IdentityID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnkiCard
	for rows.Next() {
		var i AnkiCard
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SourceType,
			&i.SourceID,
			&i.Front,
			&i.Back,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAnkiCardsExported = `-- name: MarkAnkiCardsExported :exec
UPDATE anki_cards SET status = 'exported'
WHERE identity_id = $1 AND id = ANY($2::uuid[]) AND status = 'approved'
`

type MarkAnkiCardsExportedParams struct {
	IdentityID string
	Ids        []pgtype.UUID
}

// Restricted to status = 'approved' so calling this twice with the same
// ids (e.g. a retried request) is a safe no-op the second time.
func (q *Queries) MarkAnkiCardsExported(ctx context.Context, arg MarkAnkiCardsExportedParams) error {
	_, err := q.db.Exec(ctx, markAnkiCardsExported, arg.IdentityID, arg.Ids)
	return err
}

const updateAnkiCardStatus = `-- name: UpdateAnkiCardStatus :one
UPDATE anki_cards SET status = $3
WHERE id = $1 AND identity_id = $2
RETURNING id, identity_id, source_type, source_id, front, back, notes, status, created_at
`

type UpdateAnkiCardStatusParams struct {
	ID         pgtype.UUID
	IdentityID string
	Status     string
}

func (q *Queries) UpdateAnkiCardStatus(ctx context.Context, arg UpdateAnkiCardStatusParams) (AnkiCard, error) {
	row := q.db.QueryRow(ctx, updateAnkiCardStatus, arg.ID, arg.IdentityID, arg.Status)
	var i AnkiCard
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceType,
		&i.SourceID,
		&i.Front,
		&i.Back,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
