// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apitokens.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLiveAPITokenByHash = `-- name: GetLiveAPITokenByHash :one
SELECT id, identity_id, scopes
FROM api_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

type GetLiveAPITokenByHashRow struct {
	ID         pgtype.UUID
	IdentityID string
	Scopes     string
}

// GetLiveAPITokenByHash is the authentication lookup, run on every API
// request. "Live" is the whole point: a revoked token must stop working
// immediately, so the predicate is here rather than in Go where a future
// caller could omit it.
func (q *Queries) GetLiveAPITokenByHash(ctx context.Context, tokenHash string) (GetLiveAPITokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getLiveAPITokenByHash, tokenHash)
	var i GetLiveAPITokenByHashRow
	err := row.Scan(&i.ID, &i.IdentityID, &i.Scopes)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :exec

INSERT INTO api_tokens (id, identity_id, name, token_hash, scopes)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAPITokenParams struct {
	ID         pgtype.UUID
	IdentityID string
	Name       string
	TokenHash  string
	Scopes     string
}

// API tokens for non-browser clients. See migration 00027 for why only
// the hash is stored.
//
// api_tokens is deliberately NOT in softdelete_guard_test.go's
// guardedTables: revoked_at is not a learner hiding their own content
// from every read surface, it is a credential being switched off. The
// one place that must respect it is authentication, and
// GetLiveAPITokenByHash below is that place — which is why the
// predicate is spelled out there rather than left to a caller.
func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error {
	_, err := q.db.Exec(ctx, insertAPIToken,
		arg.ID,
		arg.IdentityID,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
	)
	return err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, scopes, created_at, last_used_at, revoked_at
FROM api_tokens
WHERE identity_id = $1
ORDER BY created_at DESC
`

type ListAPITokensRow struct {
	ID         pgtype.UUID
	Name       string
	Scopes     string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

// ListAPITokens shows a learner their own tokens, including revoked
// ones: "this app's token was revoked on the 3rd" is exactly what you
// want to see when auditing which reader apps can write to your record.
func (q *Queries) ListAPITokens(ctx context.Context, identityID string) ([]ListAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAPITokens, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPITokensRow
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens
SET revoked_at = now()
WHERE id = $1 AND identity_id = $2 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	ID         pgtype.UUID
	IdentityID string
}

// RevokeAPIToken is identity-scoped so that knowing a token id is not
// enough to switch off someone else's client.
func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.IdentityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPITokenLastUsed = `-- name: TouchAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPITokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPITokenLastUsed, id)
	return err
}
