// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConversationBySession = `-- name: GetConversationBySession :one
SELECT id, session_id, identity_id, created_at, updated_at
FROM conversations
WHERE session_id = $1 AND identity_id = $2
`

type GetConversationBySessionParams struct {
	SessionID  pgtype.UUID
	IdentityID string
}

func (q *Queries) GetConversationBySession(ctx context.Context, arg GetConversationBySessionParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationBySession, arg.SessionID, arg.IdentityID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConversation = `-- name: InsertConversation :one
INSERT INTO conversations (id, session_id, identity_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, identity_id, created_at, updated_at
`

type InsertConversationParams struct {
	ID         pgtype.UUID
	SessionID  pgtype.UUID
	IdentityID string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, insertConversation,
		arg.ID,
		arg.SessionID,
		arg.IdentityID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConversationTurn = `-- name: InsertConversationTurn :execrows
INSERT INTO conversation_turns (id, conversation_id, position, learner_text, reply, reply_en, followup, corrections, ai_request_id, created_at)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
WHERE EXISTS (SELECT 1 FROM conversations c WHERE c.id = $2 AND c.identity_id = $11)
`

type InsertConversationTurnParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Position       int32
	LearnerText    string
	Reply          string
	ReplyEn        string
	Followup       string
	Corrections    []byte
	AiRequestID    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	IdentityID     string
}

// Identity-scoped via a join to conversations — the same "never trust
// the caller, check via a join" pattern db/queries/lessons.sql's
// InsertLessonObservation uses: nothing is written unless
// conversation_id actually belongs to identity_id. :execrows lets the
// caller tell "wrote" from "no such conversation for this identity"
// apart — zero rows affected maps to storage.ErrNotFound.
func (q *Queries) InsertConversationTurn(ctx context.Context, arg InsertConversationTurnParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertConversationTurn,
		arg.ID,
		arg.ConversationID,
		arg.Position,
		arg.LearnerText,
		arg.Reply,
		arg.ReplyEn,
		arg.Followup,
		arg.Corrections,
		arg.AiRequestID,
		arg.CreatedAt,
		arg.IdentityID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listConversationTurns = `-- name: ListConversationTurns :many
SELECT t.id, t.conversation_id, t.position, t.learner_text, t.reply, t.reply_en, t.followup, t.corrections, t.ai_request_id, t.created_at, c.session_id
FROM conversation_turns t
JOIN conversations c ON t.conversation_id = c.id
WHERE t.conversation_id = $1 AND c.identity_id = $2
ORDER BY t.position ASC, t.created_at ASC
`

type ListConversationTurnsParams struct {
	ConversationID pgtype.UUID
	IdentityID     string
}

type ListConversationTurnsRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Position       int32
	LearnerText    string
	Reply          string
	ReplyEn        string
	Followup       string
	Corrections    []byte
	AiRequestID    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	SessionID      pgtype.UUID
}

// Scoped via the same join, oldest first (Position ascending, t.created_at
// ASC as a tiebreak — Finding I-5: position is computed client-side with
// no DB-level dedup beyond the 00022 migration's UNIQUE(conversation_id,
// position), so two concurrent turns are still ordering-ambiguous by
// position alone if a duplicate somehow lands; created_at makes the
// order deterministic instead of database/driver-dependent). c.session_id
// is selected alongside conversation_turns' own columns so
// fromConversationTurnRow (postgres/conversations.go) can populate
// storage.ConversationTurn.SessionID on the read path — conversation_turns
// itself carries no session_id column (see the 00021 migration), only
// conversation_id, so this join is the only way back to it.
func (q *Queries) ListConversationTurns(ctx context.Context, arg ListConversationTurnsParams) ([]ListConversationTurnsRow, error) {
	rows, err := q.db.Query(ctx, listConversationTurns, arg.ConversationID, arg.IdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationTurnsRow
	for rows.Next() {
		var i ListConversationTurnsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Position,
			&i.LearnerText,
			&i.Reply,
			&i.ReplyEn,
			&i.Followup,
			&i.Corrections,
			&i.AiRequestID,
			&i.CreatedAt,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
