// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDocument = `-- name: GetDocument :one
SELECT id, session_id, identity_id, content, version, updated_at
FROM documents
WHERE id = $1 AND identity_id = $2
`

type GetDocumentParams struct {
	ID         pgtype.UUID
	IdentityID string
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.IdentityID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Content,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentBySession = `-- name: GetDocumentBySession :one
SELECT id, session_id, identity_id, content, version, updated_at
FROM documents
WHERE session_id = $1 AND identity_id = $2
`

type GetDocumentBySessionParams struct {
	SessionID  pgtype.UUID
	IdentityID string
}

func (q *Queries) GetDocumentBySession(ctx context.Context, arg GetDocumentBySessionParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentBySession, arg.SessionID, arg.IdentityID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Content,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO documents (id, session_id, identity_id, content, version, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_id, identity_id, content, version, updated_at
`

type InsertDocumentParams struct {
	ID         pgtype.UUID
	SessionID  pgtype.UUID
	IdentityID string
	Content    string
	Version    int32
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.ID,
		arg.SessionID,
		arg.IdentityID,
		arg.Content,
		arg.Version,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Content,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocumentVersion = `-- name: InsertDocumentVersion :exec
INSERT INTO document_versions (document_id, version, content, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertDocumentVersionParams struct {
	DocumentID pgtype.UUID
	Version    int32
	Content    string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) error {
	_, err := q.db.Exec(ctx, insertDocumentVersion,
		arg.DocumentID,
		arg.Version,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT dv.id, dv.document_id, dv.version, dv.content, dv.created_at
FROM document_versions dv
JOIN documents d ON d.id = dv.document_id
WHERE dv.document_id = $1 AND d.identity_id = $2
ORDER BY dv.version DESC
LIMIT $3
`

type ListDocumentVersionsParams struct {
	DocumentID pgtype.UUID
	IdentityID string
	Limit      int32
}

func (q *Queries) ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, arg.DocumentID, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentVersion
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Version,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentContent = `-- name: UpdateDocumentContent :one
UPDATE documents
SET content = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND identity_id = $2
RETURNING id, session_id, identity_id, content, version, updated_at
`

type UpdateDocumentContentParams struct {
	ID         pgtype.UUID
	IdentityID string
	Content    string
}

func (q *Queries) UpdateDocumentContent(ctx context.Context, arg UpdateDocumentContentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentContent, arg.ID, arg.IdentityID, arg.Content)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Content,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
