// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDocument = `-- name: GetDocument :one
SELECT id, session_id, identity_id, content, version, updated_at
FROM documents
WHERE documents.id = $1 AND documents.identity_id = $2
  AND EXISTS (SELECT 1 FROM sessions s WHERE s.id = documents.session_id AND s.deleted_at IS NULL)
`

type GetDocumentParams struct {
	ID         pgtype.UUID
	IdentityID string
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.IdentityID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Content,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentBySession = `-- name: GetDocumentBySession :one

SELECT id, session_id, identity_id, content, version, updated_at
FROM documents
WHERE documents.session_id = $1 AND documents.identity_id = $2
  AND EXISTS (SELECT 1 FROM sessions s WHERE s.id = documents.session_id AND s.deleted_at IS NULL)
`

type GetDocumentBySessionParams struct {
	SessionID  pgtype.UUID
	IdentityID string
}

// Soft delete, session cascade (Phase 4 Task D).
//
// documents and document_versions carry no deleted_at of their own: a
// document belongs to exactly one session (UNIQUE documents.session_id,
// 00003 migration), so "is this document deleted?" has one answer —
// "is its session deleted?". Every query below therefore tests the
// OWNING SESSION's deleted_at, spelled the same way each time:
//
//	AND EXISTS (SELECT 1 FROM sessions s
//	             WHERE s.id = <docs>.session_id AND s.deleted_at IS NULL)
//
// EXISTS rather than a JOIN so the projection stays exactly the
// documents table's own column list and sqlc keeps emitting the plain
// Document row struct. internal/adapters/postgres/softdelete_guard_test.go
// fails the build if a new query in this file omits the predicate
// without an explicit, reasoned exemption.
func (q *Queries) GetDocumentBySession(ctx context.Context, arg GetDocumentBySessionParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentBySession, arg.SessionID, arg.IdentityID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Content,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO documents (id, session_id, identity_id, content, version, updated_at)
SELECT $1, $2, $3, $4, $5, $6
WHERE EXISTS (SELECT 1 FROM sessions s WHERE s.id = $2 AND s.deleted_at IS NULL)
RETURNING id, session_id, identity_id, content, version, updated_at
`

type InsertDocumentParams struct {
	ID         pgtype.UUID
	SessionID  pgtype.UUID
	IdentityID string
	Content    string
	Version    int32
	UpdatedAt  pgtype.Timestamptz
}

// Guarded, not a bare INSERT: postgres/documents.go's
// GetOrCreateForSession falls through to this the moment
// GetDocumentBySession finds nothing — which, now that that query
// filters deleted sessions, includes "the session was deleted and its
// document is hidden". Without the guard that fallthrough would try to
// insert a SECOND document for the same session_id and hit the UNIQUE
// index as a 500 instead of a clean miss. Zero rows here surfaces as
// pgx.ErrNoRows, which the adapter maps to storage.ErrNotFound.
func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.ID,
		arg.SessionID,
		arg.IdentityID,
		arg.Content,
		arg.Version,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Content,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocumentVersion = `-- name: InsertDocumentVersion :exec
INSERT INTO document_versions (document_id, version, content, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertDocumentVersionParams struct {
	DocumentID pgtype.UUID
	Version    int32
	Content    string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) error {
	_, err := q.db.Exec(ctx, insertDocumentVersion,
		arg.DocumentID,
		arg.Version,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT dv.id, dv.document_id, dv.version, dv.content, dv.created_at
FROM document_versions dv
JOIN documents d ON d.id = dv.document_id
WHERE dv.document_id = $1 AND d.identity_id = $2
  AND EXISTS (SELECT 1 FROM sessions s WHERE s.id = d.session_id AND s.deleted_at IS NULL)
ORDER BY dv.version DESC
LIMIT $3
`

type ListDocumentVersionsParams struct {
	DocumentID pgtype.UUID
	IdentityID string
	Limit      int32
}

func (q *Queries) ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, arg.DocumentID, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentVersion
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Version,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentContent = `-- name: UpdateDocumentContent :one
UPDATE documents
SET content = $3, version = version + 1, updated_at = now()
WHERE documents.id = $1 AND documents.identity_id = $2
  AND EXISTS (SELECT 1 FROM sessions s WHERE s.id = documents.session_id AND s.deleted_at IS NULL)
RETURNING id, session_id, identity_id, content, version, updated_at
`

type UpdateDocumentContentParams struct {
	ID         pgtype.UUID
	IdentityID string
	Content    string
}

// The predicate matters more here than on any read: POST /documents/{id}
// autosaves by document id alone and never resolves the session, so
// without this a deleted session's document would stay fully writable
// from a stale tab. Zero rows maps to storage.ErrNotFound in the
// adapter, the same miss a wrong identity already produces.
func (q *Queries) UpdateDocumentContent(ctx context.Context, arg UpdateDocumentContentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentContent, arg.ID, arg.IdentityID, arg.Content)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.IdentityID,
		&i.Content,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
