// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExercise = `-- name: GetExercise :one
SELECT payload FROM exercises WHERE id = $1 AND identity_id = $2
`

type GetExerciseParams struct {
	ID         pgtype.UUID
	IdentityID string
}

func (q *Queries) GetExercise(ctx context.Context, arg GetExerciseParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getExercise, arg.ID, arg.IdentityID)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const insertExercise = `-- name: InsertExercise :exec
INSERT INTO exercises (id, identity_id, session_id, concept_slug, type, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertExerciseParams struct {
	ID          pgtype.UUID
	IdentityID  string
	SessionID   pgtype.UUID
	ConceptSlug string
	Type        string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertExercise(ctx context.Context, arg InsertExerciseParams) error {
	_, err := q.db.Exec(ctx, insertExercise,
		arg.ID,
		arg.IdentityID,
		arg.SessionID,
		arg.ConceptSlug,
		arg.Type,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const insertExerciseAttempt = `-- name: InsertExerciseAttempt :exec
INSERT INTO exercise_attempts (id, exercise_id, response, correct, score, feedback, confidence, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertExerciseAttemptParams struct {
	ID         pgtype.UUID
	ExerciseID pgtype.UUID
	Response   string
	Correct    pgtype.Bool
	Score      pgtype.Int4
	Feedback   []byte
	Confidence pgtype.Int4
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertExerciseAttempt(ctx context.Context, arg InsertExerciseAttemptParams) error {
	_, err := q.db.Exec(ctx, insertExerciseAttempt,
		arg.ID,
		arg.ExerciseID,
		arg.Response,
		arg.Correct,
		arg.Score,
		arg.Feedback,
		arg.Confidence,
		arg.CreatedAt,
	)
	return err
}
