// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCorrection = `-- name: InsertCorrection :exec
INSERT INTO corrections (
    id, feedback_request_id, position, original, replacement,
    type, severity, explanation_ja, explanation_en, status, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertCorrectionParams struct {
	ID                pgtype.UUID
	FeedbackRequestID pgtype.UUID
	Position          int32
	Original          string
	Replacement       string
	Type              string
	Severity          string
	ExplanationJa     string
	ExplanationEn     string
	Status            string
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertCorrection(ctx context.Context, arg InsertCorrectionParams) error {
	_, err := q.db.Exec(ctx, insertCorrection,
		arg.ID,
		arg.FeedbackRequestID,
		arg.Position,
		arg.Original,
		arg.Replacement,
		arg.Type,
		arg.Severity,
		arg.ExplanationJa,
		arg.ExplanationEn,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertCorrectionConcept = `-- name: InsertCorrectionConcept :exec
INSERT INTO correction_concepts (correction_id, concept_slug, resolved)
VALUES ($1, $2, $3)
ON CONFLICT (correction_id, concept_slug) DO NOTHING
`

type InsertCorrectionConceptParams struct {
	CorrectionID pgtype.UUID
	ConceptSlug  string
	Resolved     bool
}

func (q *Queries) InsertCorrectionConcept(ctx context.Context, arg InsertCorrectionConceptParams) error {
	_, err := q.db.Exec(ctx, insertCorrectionConcept, arg.CorrectionID, arg.ConceptSlug, arg.Resolved)
	return err
}

const insertFeedbackRequest = `-- name: InsertFeedbackRequest :exec
INSERT INTO feedback_requests (
    id, identity_id, session_id, document_id,
    selection_start, selection_end, selection_text, corrected_text,
    ai_request_id, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertFeedbackRequestParams struct {
	ID             pgtype.UUID
	IdentityID     string
	SessionID      pgtype.UUID
	DocumentID     pgtype.UUID
	SelectionStart int32
	SelectionEnd   int32
	SelectionText  string
	CorrectedText  string
	AiRequestID    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertFeedbackRequest(ctx context.Context, arg InsertFeedbackRequestParams) error {
	_, err := q.db.Exec(ctx, insertFeedbackRequest,
		arg.ID,
		arg.IdentityID,
		arg.SessionID,
		arg.DocumentID,
		arg.SelectionStart,
		arg.SelectionEnd,
		arg.SelectionText,
		arg.CorrectedText,
		arg.AiRequestID,
		arg.CreatedAt,
	)
	return err
}

const updateCorrectionStatus = `-- name: UpdateCorrectionStatus :one
UPDATE corrections c SET status = $3
FROM feedback_requests f
WHERE c.id = $1 AND c.feedback_request_id = f.id AND f.identity_id = $2
RETURNING c.id, c.feedback_request_id, c.position, c.original, c.replacement,
          c.type, c.severity, c.explanation_ja, c.explanation_en, c.status, f.session_id
`

type UpdateCorrectionStatusParams struct {
	ID         pgtype.UUID
	IdentityID string
	Status     string
}

type UpdateCorrectionStatusRow struct {
	ID                pgtype.UUID
	FeedbackRequestID pgtype.UUID
	Position          int32
	Original          string
	Replacement       string
	Type              string
	Severity          string
	ExplanationJa     string
	ExplanationEn     string
	Status            string
	SessionID         pgtype.UUID
}

func (q *Queries) UpdateCorrectionStatus(ctx context.Context, arg UpdateCorrectionStatusParams) (UpdateCorrectionStatusRow, error) {
	row := q.db.QueryRow(ctx, updateCorrectionStatus, arg.ID, arg.IdentityID, arg.Status)
	var i UpdateCorrectionStatusRow
	err := row.Scan(
		&i.ID,
		&i.FeedbackRequestID,
		&i.Position,
		&i.Original,
		&i.Replacement,
		&i.Type,
		&i.Severity,
		&i.ExplanationJa,
		&i.ExplanationEn,
		&i.Status,
		&i.SessionID,
	)
	return i, err
}
