// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCorrection = `-- name: GetCorrection :one
SELECT c.id, c.feedback_request_id, c.position, c.original, c.replacement,
       c.type, c.severity, c.explanation_ja, c.explanation_en, c.hint_ja, c.hint_en,
       c.status, c.attempts, c.confidence, c.revealed, f.session_id
FROM corrections c
JOIN feedback_requests f ON c.feedback_request_id = f.id
WHERE c.id = $1 AND f.identity_id = $2
`

type GetCorrectionParams struct {
	ID         pgtype.UUID
	IdentityID string
}

type GetCorrectionRow struct {
	ID                pgtype.UUID
	FeedbackRequestID pgtype.UUID
	Position          int32
	Original          string
	Replacement       string
	Type              string
	Severity          string
	ExplanationJa     string
	ExplanationEn     string
	HintJa            string
	HintEn            string
	Status            string
	Attempts          int32
	Confidence        pgtype.Int4
	Revealed          bool
	SessionID         pgtype.UUID
}

// Identity-scoped read, same join as UpdateCorrectionStatus: a
// correction that exists but belongs to another identity's feedback
// misses exactly like one that doesn't exist at all.
func (q *Queries) GetCorrection(ctx context.Context, arg GetCorrectionParams) (GetCorrectionRow, error) {
	row := q.db.QueryRow(ctx, getCorrection, arg.ID, arg.IdentityID)
	var i GetCorrectionRow
	err := row.Scan(
		&i.ID,
		&i.FeedbackRequestID,
		&i.Position,
		&i.Original,
		&i.Replacement,
		&i.Type,
		&i.Severity,
		&i.ExplanationJa,
		&i.ExplanationEn,
		&i.HintJa,
		&i.HintEn,
		&i.Status,
		&i.Attempts,
		&i.Confidence,
		&i.Revealed,
		&i.SessionID,
	)
	return i, err
}

const getCorrectionConcepts = `-- name: GetCorrectionConcepts :many
SELECT concept_slug
FROM correction_concepts
WHERE correction_id = $1 AND resolved
ORDER BY concept_slug
`

func (q *Queries) GetCorrectionConcepts(ctx context.Context, correctionID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getCorrectionConcepts, correctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var concept_slug string
		if err := rows.Scan(&concept_slug); err != nil {
			return nil, err
		}
		items = append(items, concept_slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCorrection = `-- name: InsertCorrection :exec
INSERT INTO corrections (
    id, feedback_request_id, position, original, replacement,
    type, severity, explanation_ja, explanation_en, hint_ja, hint_en, status, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertCorrectionParams struct {
	ID                pgtype.UUID
	FeedbackRequestID pgtype.UUID
	Position          int32
	Original          string
	Replacement       string
	Type              string
	Severity          string
	ExplanationJa     string
	ExplanationEn     string
	HintJa            string
	HintEn            string
	Status            string
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertCorrection(ctx context.Context, arg InsertCorrectionParams) error {
	_, err := q.db.Exec(ctx, insertCorrection,
		arg.ID,
		arg.FeedbackRequestID,
		arg.Position,
		arg.Original,
		arg.Replacement,
		arg.Type,
		arg.Severity,
		arg.ExplanationJa,
		arg.ExplanationEn,
		arg.HintJa,
		arg.HintEn,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertCorrectionConcept = `-- name: InsertCorrectionConcept :exec
INSERT INTO correction_concepts (correction_id, concept_slug, resolved)
VALUES ($1, $2, $3)
ON CONFLICT (correction_id, concept_slug) DO NOTHING
`

type InsertCorrectionConceptParams struct {
	CorrectionID pgtype.UUID
	ConceptSlug  string
	Resolved     bool
}

func (q *Queries) InsertCorrectionConcept(ctx context.Context, arg InsertCorrectionConceptParams) error {
	_, err := q.db.Exec(ctx, insertCorrectionConcept, arg.CorrectionID, arg.ConceptSlug, arg.Resolved)
	return err
}

const insertFeedbackRequest = `-- name: InsertFeedbackRequest :exec
INSERT INTO feedback_requests (
    id, identity_id, session_id, document_id,
    selection_start, selection_end, selection_text, corrected_text,
    ai_request_id, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertFeedbackRequestParams struct {
	ID             pgtype.UUID
	IdentityID     string
	SessionID      pgtype.UUID
	DocumentID     pgtype.UUID
	SelectionStart int32
	SelectionEnd   int32
	SelectionText  string
	CorrectedText  string
	AiRequestID    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertFeedbackRequest(ctx context.Context, arg InsertFeedbackRequestParams) error {
	_, err := q.db.Exec(ctx, insertFeedbackRequest,
		arg.ID,
		arg.IdentityID,
		arg.SessionID,
		arg.DocumentID,
		arg.SelectionStart,
		arg.SelectionEnd,
		arg.SelectionText,
		arg.CorrectedText,
		arg.AiRequestID,
		arg.CreatedAt,
	)
	return err
}

const recordConfidence = `-- name: RecordConfidence :one
UPDATE corrections c SET confidence = $3
FROM feedback_requests f
WHERE c.id = $1 AND c.feedback_request_id = f.id AND f.identity_id = $2
RETURNING c.id, c.feedback_request_id, c.position, c.original, c.replacement,
          c.type, c.severity, c.explanation_ja, c.explanation_en, c.hint_ja, c.hint_en,
          c.status, c.attempts, c.confidence, c.revealed, f.session_id
`

type RecordConfidenceParams struct {
	ID         pgtype.UUID
	IdentityID string
	Confidence pgtype.Int4
}

type RecordConfidenceRow struct {
	ID                pgtype.UUID
	FeedbackRequestID pgtype.UUID
	Position          int32
	Original          string
	Replacement       string
	Type              string
	Severity          string
	ExplanationJa     string
	ExplanationEn     string
	HintJa            string
	HintEn            string
	Status            string
	Attempts          int32
	Confidence        pgtype.Int4
	Revealed          bool
	SessionID         pgtype.UUID
}

func (q *Queries) RecordConfidence(ctx context.Context, arg RecordConfidenceParams) (RecordConfidenceRow, error) {
	row := q.db.QueryRow(ctx, recordConfidence, arg.ID, arg.IdentityID, arg.Confidence)
	var i RecordConfidenceRow
	err := row.Scan(
		&i.ID,
		&i.FeedbackRequestID,
		&i.Position,
		&i.Original,
		&i.Replacement,
		&i.Type,
		&i.Severity,
		&i.ExplanationJa,
		&i.ExplanationEn,
		&i.HintJa,
		&i.HintEn,
		&i.Status,
		&i.Attempts,
		&i.Confidence,
		&i.Revealed,
		&i.SessionID,
	)
	return i, err
}

const retryCorrection = `-- name: RetryCorrection :one
UPDATE corrections c SET
    attempts = c.attempts + 1,
    status = CASE WHEN $3 = c.replacement THEN 'accepted' ELSE c.status END
FROM feedback_requests f
WHERE c.id = $1 AND c.feedback_request_id = f.id AND f.identity_id = $2 AND c.status = 'presented'
RETURNING c.id, c.feedback_request_id, c.position, c.original, c.replacement,
          c.type, c.severity, c.explanation_ja, c.explanation_en, c.hint_ja, c.hint_en,
          c.status, c.attempts, c.confidence, c.revealed, f.session_id
`

type RetryCorrectionParams struct {
	ID          pgtype.UUID
	IdentityID  string
	Replacement string
}

type RetryCorrectionRow struct {
	ID                pgtype.UUID
	FeedbackRequestID pgtype.UUID
	Position          int32
	Original          string
	Replacement       string
	Type              string
	Severity          string
	ExplanationJa     string
	ExplanationEn     string
	HintJa            string
	HintEn            string
	Status            string
	Attempts          int32
	Confidence        pgtype.Int4
	Revealed          bool
	SessionID         pgtype.UUID
}

// Atomic "increment attempts, and accept if (and only if) this attempt
// exactly matches replacement" — see storage.FeedbackRepository's doc
// comment on why this is one UPDATE (a single, non-racy statement, with
// the SQL '=' comparison itself deciding correctness) rather than a
// read-then-write pair. status = 'presented' in the WHERE clause is
// what confines retries to corrections still awaiting resolution.
func (q *Queries) RetryCorrection(ctx context.Context, arg RetryCorrectionParams) (RetryCorrectionRow, error) {
	row := q.db.QueryRow(ctx, retryCorrection, arg.ID, arg.IdentityID, arg.Replacement)
	var i RetryCorrectionRow
	err := row.Scan(
		&i.ID,
		&i.FeedbackRequestID,
		&i.Position,
		&i.Original,
		&i.Replacement,
		&i.Type,
		&i.Severity,
		&i.ExplanationJa,
		&i.ExplanationEn,
		&i.HintJa,
		&i.HintEn,
		&i.Status,
		&i.Attempts,
		&i.Confidence,
		&i.Revealed,
		&i.SessionID,
	)
	return i, err
}

const revealCorrection = `-- name: RevealCorrection :one
UPDATE corrections c SET revealed = true
FROM feedback_requests f
WHERE c.id = $1 AND c.feedback_request_id = f.id AND f.identity_id = $2 AND c.status = 'presented'
RETURNING c.id, c.feedback_request_id, c.position, c.original, c.replacement,
          c.type, c.severity, c.explanation_ja, c.explanation_en, c.hint_ja, c.hint_en,
          c.status, c.attempts, c.confidence, c.revealed, f.session_id
`

type RevealCorrectionParams struct {
	ID         pgtype.UUID
	IdentityID string
}

type RevealCorrectionRow struct {
	ID                pgtype.UUID
	FeedbackRequestID pgtype.UUID
	Position          int32
	Original          string
	Replacement       string
	Type              string
	Severity          string
	ExplanationJa     string
	ExplanationEn     string
	HintJa            string
	HintEn            string
	Status            string
	Attempts          int32
	Confidence        pgtype.Int4
	Revealed          bool
	SessionID         pgtype.UUID
}

func (q *Queries) RevealCorrection(ctx context.Context, arg RevealCorrectionParams) (RevealCorrectionRow, error) {
	row := q.db.QueryRow(ctx, revealCorrection, arg.ID, arg.IdentityID)
	var i RevealCorrectionRow
	err := row.Scan(
		&i.ID,
		&i.FeedbackRequestID,
		&i.Position,
		&i.Original,
		&i.Replacement,
		&i.Type,
		&i.Severity,
		&i.ExplanationJa,
		&i.ExplanationEn,
		&i.HintJa,
		&i.HintEn,
		&i.Status,
		&i.Attempts,
		&i.Confidence,
		&i.Revealed,
		&i.SessionID,
	)
	return i, err
}

const updateCorrectionStatus = `-- name: UpdateCorrectionStatus :one
UPDATE corrections c SET status = $3
FROM feedback_requests f
WHERE c.id = $1 AND c.feedback_request_id = f.id AND f.identity_id = $2
RETURNING c.id, c.feedback_request_id, c.position, c.original, c.replacement,
          c.type, c.severity, c.explanation_ja, c.explanation_en, c.hint_ja, c.hint_en,
          c.status, c.attempts, c.confidence, c.revealed, f.session_id
`

type UpdateCorrectionStatusParams struct {
	ID         pgtype.UUID
	IdentityID string
	Status     string
}

type UpdateCorrectionStatusRow struct {
	ID                pgtype.UUID
	FeedbackRequestID pgtype.UUID
	Position          int32
	Original          string
	Replacement       string
	Type              string
	Severity          string
	ExplanationJa     string
	ExplanationEn     string
	HintJa            string
	HintEn            string
	Status            string
	Attempts          int32
	Confidence        pgtype.Int4
	Revealed          bool
	SessionID         pgtype.UUID
}

func (q *Queries) UpdateCorrectionStatus(ctx context.Context, arg UpdateCorrectionStatusParams) (UpdateCorrectionStatusRow, error) {
	row := q.db.QueryRow(ctx, updateCorrectionStatus, arg.ID, arg.IdentityID, arg.Status)
	var i UpdateCorrectionStatusRow
	err := row.Scan(
		&i.ID,
		&i.FeedbackRequestID,
		&i.Position,
		&i.Original,
		&i.Replacement,
		&i.Type,
		&i.Severity,
		&i.ExplanationJa,
		&i.ExplanationEn,
		&i.HintJa,
		&i.HintEn,
		&i.Status,
		&i.Attempts,
		&i.Confidence,
		&i.Revealed,
		&i.SessionID,
	)
	return i, err
}
