// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grammar.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const conceptStats = `-- name: ConceptStats :many
SELECT gc.slug, gc.name, gc.jlpt_level,
       COUNT(oc.correction_id)::int AS encounters,
       COALESCE(MAX(oc.created_at), 'epoch'::timestamptz) AS last_seen
FROM grammar_concepts gc
LEFT JOIN (
    SELECT cc.concept_slug, cc.correction_id, c.created_at
    FROM correction_concepts cc
    JOIN corrections c ON c.id = cc.correction_id
    JOIN feedback_requests f ON f.id = c.feedback_request_id
    WHERE cc.resolved AND f.identity_id = $1
) oc ON oc.concept_slug = gc.slug
GROUP BY gc.slug, gc.name, gc.jlpt_level
ORDER BY encounters DESC, gc.jlpt_level DESC, gc.slug
`

type ConceptStatsRow struct {
	Slug       string
	Name       string
	JlptLevel  int32
	Encounters int32
	LastSeen   interface{}
}

// Scoped subquery, not a straight LEFT JOIN + WHERE: filtering
// correction_concepts/corrections/feedback_requests to the caller's
// identity has to happen INSIDE the joined subquery (oc) so that a
// concept tagged only by another identity's corrections still
// produces a row here (encounters=0), rather than a WHERE clause on
// the outer query dropping the grammar_concepts row entirely because
// its only correction_concepts match belongs to someone else.
func (q *Queries) ConceptStats(ctx context.Context, identityID string) ([]ConceptStatsRow, error) {
	rows, err := q.db.Query(ctx, conceptStats, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConceptStatsRow
	for rows.Next() {
		var i ConceptStatsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.JlptLevel,
			&i.Encounters,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const correctionsForConcept = `-- name: CorrectionsForConcept :many
SELECT c.id, c.feedback_request_id, c.position, c.original, c.replacement,
       c.type, c.severity, c.explanation_ja, c.explanation_en, c.status, f.session_id
FROM corrections c
JOIN correction_concepts cc ON cc.correction_id = c.id AND cc.concept_slug = $2 AND cc.resolved
JOIN feedback_requests f ON f.id = c.feedback_request_id AND f.identity_id = $1
WHERE NOT (c.status = 'presented' AND c.revealed = false AND (c.hint_ja <> '' OR c.hint_en <> ''))
ORDER BY c.created_at DESC
LIMIT $3
`

type CorrectionsForConceptParams struct {
	IdentityID  string
	ConceptSlug string
	Limit       int32
}

type CorrectionsForConceptRow struct {
	ID                pgtype.UUID
	FeedbackRequestID pgtype.UUID
	Position          int32
	Original          string
	Replacement       string
	Type              string
	Severity          string
	ExplanationJa     string
	ExplanationEn     string
	Status            string
	SessionID         pgtype.UUID
}

// Excludes gated socratic corrections outright (WHERE NOT, not a
// caller-side blank-the-field patch): a correction that's still
// "presented", unrevealed, and carrying a hint is a still-gated
// socratic round (see internal/adapters/http/api.go's
// isGatedCorrection, the same predicate). Its Replacement is the
// answer the learner hasn't earned yet, so the row is dropped
// entirely — a gated correction must not even advertise its
// existence on the /grammar/{slug} concept detail page, let alone
// leak its Replacement there.
func (q *Queries) CorrectionsForConcept(ctx context.Context, arg CorrectionsForConceptParams) ([]CorrectionsForConceptRow, error) {
	rows, err := q.db.Query(ctx, correctionsForConcept, arg.IdentityID, arg.ConceptSlug, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CorrectionsForConceptRow
	for rows.Next() {
		var i CorrectionsForConceptRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedbackRequestID,
			&i.Position,
			&i.Original,
			&i.Replacement,
			&i.Type,
			&i.Severity,
			&i.ExplanationJa,
			&i.ExplanationEn,
			&i.Status,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGrammarConcept = `-- name: GetGrammarConcept :one
SELECT slug, name, jlpt_level, description, examples, related, prerequisites
FROM grammar_concepts
WHERE slug = $1
`

func (q *Queries) GetGrammarConcept(ctx context.Context, slug string) (GrammarConcept, error) {
	row := q.db.QueryRow(ctx, getGrammarConcept, slug)
	var i GrammarConcept
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.JlptLevel,
		&i.Description,
		&i.Examples,
		&i.Related,
		&i.Prerequisites,
	)
	return i, err
}

const listGrammarConcepts = `-- name: ListGrammarConcepts :many
SELECT slug, name, jlpt_level, description, examples, related, prerequisites
FROM grammar_concepts
ORDER BY jlpt_level DESC, slug
`

func (q *Queries) ListGrammarConcepts(ctx context.Context) ([]GrammarConcept, error) {
	rows, err := q.db.Query(ctx, listGrammarConcepts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrammarConcept
	for rows.Next() {
		var i GrammarConcept
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.JlptLevel,
			&i.Description,
			&i.Examples,
			&i.Related,
			&i.Prerequisites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGrammarConcept = `-- name: UpsertGrammarConcept :exec
INSERT INTO grammar_concepts (slug, name, jlpt_level, description, examples, related, prerequisites)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (slug) DO UPDATE SET
    name          = EXCLUDED.name,
    jlpt_level    = EXCLUDED.jlpt_level,
    description   = EXCLUDED.description,
    examples      = EXCLUDED.examples,
    related       = EXCLUDED.related,
    prerequisites = EXCLUDED.prerequisites
`

type UpsertGrammarConceptParams struct {
	Slug          string
	Name          string
	JlptLevel     int32
	Description   string
	Examples      []byte
	Related       []byte
	Prerequisites []byte
}

func (q *Queries) UpsertGrammarConcept(ctx context.Context, arg UpsertGrammarConceptParams) error {
	_, err := q.db.Exec(ctx, upsertGrammarConcept,
		arg.Slug,
		arg.Name,
		arg.JlptLevel,
		arg.Description,
		arg.Examples,
		arg.Related,
		arg.Prerequisites,
	)
	return err
}
