// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package sqlcgen

import (
	"context"
)

const getIdentity = `-- name: GetIdentity :one
SELECT id, display_name, attributes, created_at FROM identities WHERE id = $1
`

func (q *Queries) GetIdentity(ctx context.Context, id string) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentity, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertIdentity = `-- name: UpsertIdentity :exec
INSERT INTO identities (id, display_name, attributes)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET display_name = EXCLUDED.display_name, attributes = EXCLUDED.attributes
`

type UpsertIdentityParams struct {
	ID          string
	DisplayName string
	Attributes  []byte
}

func (q *Queries) UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) error {
	_, err := q.db.Exec(ctx, upsertIdentity, arg.ID, arg.DisplayName, arg.Attributes)
	return err
}
