// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendLearningEvent = `-- name: AppendLearningEvent :exec
INSERT INTO learning_events (id, identity_id, session_id, type, subject, evidence, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type AppendLearningEventParams struct {
	ID         pgtype.UUID
	IdentityID string
	SessionID  pgtype.UUID
	Type       string
	Subject    string
	Evidence   []byte
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) AppendLearningEvent(ctx context.Context, arg AppendLearningEventParams) error {
	_, err := q.db.Exec(ctx, appendLearningEvent,
		arg.ID,
		arg.IdentityID,
		arg.SessionID,
		arg.Type,
		arg.Subject,
		arg.Evidence,
		arg.OccurredAt,
	)
	return err
}

const listRecentLearningEvents = `-- name: ListRecentLearningEvents :many
SELECT id, identity_id, session_id, type, subject, evidence, occurred_at
FROM learning_events
WHERE identity_id = $1 AND ($2::uuid IS NULL OR session_id = $2)
ORDER BY occurred_at DESC
LIMIT $3
`

type ListRecentLearningEventsParams struct {
	IdentityID string
	Column2    pgtype.UUID
	Limit      int32
}

func (q *Queries) ListRecentLearningEvents(ctx context.Context, arg ListRecentLearningEventsParams) ([]LearningEvent, error) {
	rows, err := q.db.Query(ctx, listRecentLearningEvents, arg.IdentityID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningEvent
	for rows.Next() {
		var i LearningEvent
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SessionID,
			&i.Type,
			&i.Subject,
			&i.Evidence,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
