// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeLesson = `-- name: CompleteLesson :one
UPDATE lessons SET status = 'completed', completed_at = $3
WHERE id = $1 AND identity_id = $2 AND deleted_at IS NULL
RETURNING id, identity_id, plan, status, created_at, completed_at, deleted_at
`

type CompleteLessonParams struct {
	ID          pgtype.UUID
	IdentityID  string
	CompletedAt pgtype.Timestamptz
}

// Run inside the SAME transaction as InsertLessonObservation below —
// see postgres/lessons.go's CompleteWithObservation, the ONLY caller of
// either query: a lesson must never end up "completed" without its
// triggering observation actually attached, or vice versa. Not called
// standalone by anything else. The deleted_at test is the same one Get
// applies: a deleted lesson is invisible to reads, so it must not be
// completable either — otherwise the tutor's observation would attach
// to something the learner can no longer see.
func (q *Queries) CompleteLesson(ctx context.Context, arg CompleteLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, completeLesson, arg.ID, arg.IdentityID, arg.CompletedAt)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLesson = `-- name: GetLesson :one
SELECT id, identity_id, plan, status, created_at, completed_at, deleted_at
FROM lessons
WHERE id = $1 AND identity_id = $2 AND deleted_at IS NULL
`

type GetLessonParams struct {
	ID         pgtype.UUID
	IdentityID string
}

func (q *Queries) GetLesson(ctx context.Context, arg GetLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLesson, arg.ID, arg.IdentityID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertLesson = `-- name: InsertLesson :exec
INSERT INTO lessons (id, identity_id, plan, status, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertLessonParams struct {
	ID         pgtype.UUID
	IdentityID string
	Plan       []byte
	Status     string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertLesson(ctx context.Context, arg InsertLessonParams) error {
	_, err := q.db.Exec(ctx, insertLesson,
		arg.ID,
		arg.IdentityID,
		arg.Plan,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertLessonObservation = `-- name: InsertLessonObservation :execrows
INSERT INTO lesson_observations (id, lesson_id, author, notes, subjects, created_at)
SELECT $1, $2, $3, $4, $5, $6
WHERE EXISTS (SELECT 1 FROM lessons l WHERE l.id = $2 AND l.identity_id = $7 AND l.deleted_at IS NULL)
`

type InsertLessonObservationParams struct {
	ID         pgtype.UUID
	LessonID   pgtype.UUID
	Author     string
	Notes      string
	Subjects   []byte
	CreatedAt  pgtype.Timestamptz
	IdentityID string
}

// Run inside the SAME transaction as CompleteLesson above, by
// postgres/lessons.go's CompleteWithObservation. Identity check via a
// join to lessons itself, the same "never trust the caller, check via
// a join" shape UpsertAIRating (ai_ratings.sql) uses: nothing is
// written unless lesson_id actually belongs to identity_id AND is not
// soft-deleted. :execrows lets the caller tell "wrote" from "no such
// lesson for this identity" apart — zero rows affected means the
// latter, mapped to storage.ErrNotFound (and, since this runs inside
// the same transaction, rolls back CompleteLesson's status flip too).
func (q *Queries) InsertLessonObservation(ctx context.Context, arg InsertLessonObservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLessonObservation,
		arg.ID,
		arg.LessonID,
		arg.Author,
		arg.Notes,
		arg.Subjects,
		arg.CreatedAt,
		arg.IdentityID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLessonObservations = `-- name: ListLessonObservations :many
SELECT o.id, o.lesson_id, o.author, o.notes, o.subjects, o.created_at
FROM lesson_observations o
JOIN lessons l ON o.lesson_id = l.id
WHERE o.lesson_id = $1 AND l.identity_id = $2 AND l.deleted_at IS NULL
ORDER BY o.created_at DESC
`

type ListLessonObservationsParams struct {
	LessonID   pgtype.UUID
	IdentityID string
}

// Scoped via the same join, but filters rather than errors on a
// mismatch — see storage.LessonRepository.Observations' doc comment
// for why (the caller always Gets the lesson first, which does error).
// A soft-deleted lesson's observations are filtered here for the same
// reason: the lesson itself is unreachable, so its notes must be too.
func (q *Queries) ListLessonObservations(ctx context.Context, arg ListLessonObservationsParams) ([]LessonObservation, error) {
	rows, err := q.db.Query(ctx, listLessonObservations, arg.LessonID, arg.IdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonObservation
	for rows.Next() {
		var i LessonObservation
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Author,
			&i.Notes,
			&i.Subjects,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessons = `-- name: ListLessons :many
SELECT id, identity_id, plan, status, created_at, completed_at, deleted_at
FROM lessons
WHERE identity_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListLessons(ctx context.Context, identityID string) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessons, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Plan,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreLesson = `-- name: RestoreLesson :execrows
UPDATE lessons SET deleted_at = NULL
WHERE id = $1 AND identity_id = $2
`

type RestoreLessonParams struct {
	ID         pgtype.UUID
	IdentityID string
}

// The way back — see SoftDeleteSession/RestoreSession in
// db/queries/sessions.sql.
func (q *Queries) RestoreLesson(ctx context.Context, arg RestoreLessonParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreLesson, arg.ID, arg.IdentityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteLesson = `-- name: SoftDeleteLesson :execrows
UPDATE lessons SET deleted_at = COALESCE(deleted_at, $3::timestamptz)
WHERE id = $1 AND identity_id = $2
`

type SoftDeleteLessonParams struct {
	ID         pgtype.UUID
	IdentityID string
	At         pgtype.Timestamptz
}

// The learner's "delete this lesson guide" (Phase 4 Task D). Identity-
// scoped, idempotent, and non-destructive for exactly the reasons
// db/queries/sessions.sql's SoftDeleteSession spells out — read that
// comment; this is the same statement over a different table, on
// purpose, so there is one shape to understand rather than three.
func (q *Queries) SoftDeleteLesson(ctx context.Context, arg SoftDeleteLessonParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLesson, arg.ID, arg.IdentityID, arg.At)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
