// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Identity struct {
	ID          string
	DisplayName string
	Attributes  []byte
	CreatedAt   pgtype.Timestamptz
}

type Session struct {
	ID         pgtype.UUID
	IdentityID string
	Title      string
	Purpose    string
	Profile    []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
