// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID         pgtype.UUID
	SessionID  pgtype.UUID
	IdentityID string
	Content    string
	Version    int32
	UpdatedAt  pgtype.Timestamptz
}

type DocumentVersion struct {
	ID         int64
	DocumentID pgtype.UUID
	Version    int32
	Content    string
	CreatedAt  pgtype.Timestamptz
}

type Identity struct {
	ID          string
	DisplayName string
	Attributes  []byte
	CreatedAt   pgtype.Timestamptz
}

type Session struct {
	ID         pgtype.UUID
	IdentityID string
	Title      string
	Purpose    string
	Profile    []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
