// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentRun struct {
	ID            pgtype.UUID
	IdentityID    string
	SessionID     pgtype.UUID
	Agent         string
	PromptName    string
	PromptVersion string
	Status        string
	Turns         int32
	StartedAt     pgtype.Timestamptz
	EndedAt       pgtype.Timestamptz
	Error         string
	System        string
	Input         string
	Output        string
}

type AgentTurn struct {
	ID         pgtype.UUID
	AgentRunID pgtype.UUID
	TurnNumber int32
	Text       string
	CreatedAt  pgtype.Timestamptz
}

type AiRating struct {
	ID          pgtype.UUID
	AiRequestID pgtype.UUID
	IdentityID  string
	Rating      int32
	CreatedAt   pgtype.Timestamptz
}

type AiRequest struct {
	ID            pgtype.UUID
	IdentityID    string
	SessionID     pgtype.UUID
	Capability    string
	Provider      string
	Model         string
	PromptName    string
	PromptVersion string
	LatencyMs     int32
	InputTokens   int32
	OutputTokens  int32
	CostUsd       pgtype.Numeric
	Success       bool
	Error         string
	CreatedAt     pgtype.Timestamptz
	Agent         string
}

type AnkiCard struct {
	ID         pgtype.UUID
	IdentityID string
	SourceType string
	SourceID   string
	Front      string
	Back       string
	Notes      string
	Status     string
	CreatedAt  pgtype.Timestamptz
}

// Operator settings (e.g. AI model/effort overrides) — GLOBAL, NOT identity-scoped. Do not add an identity_id column here; see internal/ports/storage.SettingsRepository.
type AppSetting struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}

type Conversation struct {
	ID         pgtype.UUID
	SessionID  pgtype.UUID
	IdentityID string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ConversationTurn struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Position       int32
	LearnerText    string
	Reply          string
	ReplyEn        string
	Followup       string
	Corrections    []byte
	AiRequestID    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Correction struct {
	ID                pgtype.UUID
	FeedbackRequestID pgtype.UUID
	Position          int32
	Original          string
	Replacement       string
	Type              string
	Severity          string
	ExplanationJa     string
	ExplanationEn     string
	Status            string
	CreatedAt         pgtype.Timestamptz
	HintJa            string
	HintEn            string
	Attempts          int32
	Confidence        pgtype.Int4
	Revealed          bool
}

type CorrectionConcept struct {
	CorrectionID pgtype.UUID
	ConceptSlug  string
	Resolved     bool
}

type Document struct {
	ID         pgtype.UUID
	SessionID  pgtype.UUID
	IdentityID string
	Content    string
	Version    int32
	UpdatedAt  pgtype.Timestamptz
}

type DocumentVersion struct {
	ID         int64
	DocumentID pgtype.UUID
	Version    int32
	Content    string
	CreatedAt  pgtype.Timestamptz
}

type Exercise struct {
	ID          pgtype.UUID
	IdentityID  string
	SessionID   pgtype.UUID
	ConceptSlug string
	Type        string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

type ExerciseAttempt struct {
	ID         pgtype.UUID
	ExerciseID pgtype.UUID
	Response   string
	Correct    pgtype.Bool
	Score      pgtype.Int4
	Feedback   []byte
	Confidence pgtype.Int4
	CreatedAt  pgtype.Timestamptz
}

type FeedbackRequest struct {
	ID             pgtype.UUID
	IdentityID     string
	SessionID      pgtype.UUID
	DocumentID     pgtype.UUID
	SelectionStart int32
	SelectionEnd   int32
	SelectionText  string
	CorrectedText  string
	AiRequestID    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type GrammarConcept struct {
	Slug          string
	Name          string
	JlptLevel     int32
	Description   string
	Examples      []byte
	Related       []byte
	Prerequisites []byte
}

type Identity struct {
	ID          string
	DisplayName string
	Attributes  []byte
	CreatedAt   pgtype.Timestamptz
}

type LearnerObservation struct {
	ID          pgtype.UUID
	IdentityID  string
	Kind        string
	SubjectType string
	Subject     string
	Confidence  float64
	Evidence    []byte
	FirstSeen   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type LearnerPriority struct {
	IdentityID  string
	SubjectType string
	Subject     string
	Score       float64
	Reason      string
	UpdatedAt   pgtype.Timestamptz
}

type LearningEvent struct {
	ID         pgtype.UUID
	IdentityID string
	SessionID  pgtype.UUID
	Type       string
	Subject    string
	Evidence   []byte
	OccurredAt pgtype.Timestamptz
}

type Lesson struct {
	ID          pgtype.UUID
	IdentityID  string
	Plan        []byte
	Status      string
	CreatedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

type LessonObservation struct {
	ID        pgtype.UUID
	LessonID  pgtype.UUID
	Author    string
	Notes     string
	Subjects  []byte
	CreatedAt pgtype.Timestamptz
}

type RetrievalItem struct {
	IdentityID      string
	SubjectType     string
	Subject         string
	Successes       int32
	Failures        int32
	LastSeen        pgtype.Timestamptz
	DueAt           pgtype.Timestamptz
	IntervalSeconds int64
	Confidence      float64
}

type Session struct {
	ID         pgtype.UUID
	IdentityID string
	Title      string
	Purpose    string
	Profile    []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ToolCall struct {
	ID         pgtype.UUID
	AgentRunID pgtype.UUID
	ToolName   string
	Arguments  string
	Result     string
	IsError    bool
	DurationMs int32
	CreatedAt  pgtype.Timestamptz
}

type VocabularyEvent struct {
	ID            pgtype.UUID
	IdentityID    string
	ItemID        pgtype.UUID
	Type          string
	Payload       []byte
	ClientEventID pgtype.Text
	OccurredAt    pgtype.Timestamptz
}

type VocabularyItem struct {
	ID                    pgtype.UUID
	IdentityID            string
	Expression            string
	Reading               string
	Meaning               string
	Kind                  string
	JlptLevel             int32
	Source                string
	Lookups               int32
	Productions           int32
	SuccessfulProductions int32
	FirstSeen             pgtype.Timestamptz
	LastEvent             pgtype.Timestamptz
	MeaningEn             string
	Tags                  []byte
}
