// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteObservations = `-- name: DeleteObservations :exec
DELETE FROM learner_observations WHERE identity_id = $1
`

func (q *Queries) DeleteObservations(ctx context.Context, identityID string) error {
	_, err := q.db.Exec(ctx, deleteObservations, identityID)
	return err
}

const listObservations = `-- name: ListObservations :many
SELECT id, identity_id, kind, subject_type, subject, confidence, evidence, first_seen, updated_at
FROM learner_observations
WHERE identity_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListObservations(ctx context.Context, identityID string) ([]LearnerObservation, error) {
	rows, err := q.db.Query(ctx, listObservations, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearnerObservation
	for rows.Next() {
		var i LearnerObservation
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Kind,
			&i.SubjectType,
			&i.Subject,
			&i.Confidence,
			&i.Evidence,
			&i.FirstSeen,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertObservation = `-- name: UpsertObservation :exec
INSERT INTO learner_observations (id, identity_id, kind, subject_type, subject, confidence, evidence, first_seen, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (identity_id, subject_type, subject) DO UPDATE SET
    kind       = EXCLUDED.kind,
    confidence = EXCLUDED.confidence,
    evidence   = EXCLUDED.evidence,
    updated_at = EXCLUDED.updated_at
`

type UpsertObservationParams struct {
	ID          pgtype.UUID
	IdentityID  string
	Kind        string
	SubjectType string
	Subject     string
	Confidence  float64
	Evidence    []byte
	FirstSeen   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertObservation(ctx context.Context, arg UpsertObservationParams) error {
	_, err := q.db.Exec(ctx, upsertObservation,
		arg.ID,
		arg.IdentityID,
		arg.Kind,
		arg.SubjectType,
		arg.Subject,
		arg.Confidence,
		arg.Evidence,
		arg.FirstSeen,
		arg.UpdatedAt,
	)
	return err
}
