// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outcomes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const conceptCorrectionOutcomes = `-- name: ConceptCorrectionOutcomes :many

WITH tagged AS (
    SELECT cc.concept_slug AS slug, c.created_at AS created_at
    FROM correction_concepts cc
    JOIN corrections c ON c.id = cc.correction_id
    JOIN feedback_requests f ON f.id = c.feedback_request_id
    WHERE cc.resolved AND f.identity_id = $1
),
bounds AS (
    SELECT slug,
           MIN(created_at) AS first_corrected_at,
           MAX(created_at) AS last_corrected_at,
           COUNT(*)::int AS total_corrections
    FROM tagged
    GROUP BY slug
)
SELECT gc.slug,
       gc.name,
       b.first_corrected_at::timestamptz AS first_corrected_at,
       b.last_corrected_at::timestamptz AS last_corrected_at,
       b.total_corrections,
       (SELECT COUNT(*) FROM tagged t
         WHERE t.slug = b.slug
           AND t.created_at < b.first_corrected_at + ($2::bigint * interval '1 second'))::int
         AS corrections_before,
       (SELECT COUNT(*) FROM tagged t
         WHERE t.slug = b.slug
           AND t.created_at >= $3::timestamptz)::int
         AS corrections_after
FROM bounds b
JOIN grammar_concepts gc ON gc.slug = b.slug
ORDER BY gc.slug
`

type ConceptCorrectionOutcomesParams struct {
	IdentityID string
	Column2    int64
	Column3    pgtype.Timestamptz
}

type ConceptCorrectionOutcomesRow struct {
	Slug              string
	Name              string
	FirstCorrectedAt  pgtype.Timestamptz
	LastCorrectedAt   pgtype.Timestamptz
	TotalCorrections  int32
	CorrectionsBefore int32
	CorrectionsAfter  int32
}

// Learning-outcome analytics (Phase 4 Task 9, PRD §52/§72/§73): did
// being corrected lead to better later production?
//
// Every query in this file returns RAW COUNTS AND TIMESTAMPS ONLY. Not
// one of them decides "improving", "persistent", "retired", or "not
// enough data" — those judgements, and every threshold behind them,
// live in internal/application/outcomes where a unit test can walk each
// boundary exactly (project convention; see that package's doc
// comment). The two measurement WINDOWS are parameters supplied by the
// caller from storage.OutcomeBaselineWindow/OutcomeRecentWindow, so
// this file hard-codes no duration either.
// One row per grammar concept this identity has ever been corrected on.
//
// `tagged` is the identity-scoped set of (concept, correction time)
// pairs — corrections carry no identity_id of their own, so the scope
// comes through the owning feedback_requests row, the same join every
// other identity-scoped corrections query in this codebase uses
// (analytics.sql, grammar.sql). Unresolved concept tags (a slug the
// tagger invented that isn't in the catalog) are excluded via
// cc.resolved, and the final JOIN to grammar_concepts supplies the
// display name.
//
// corrections_before counts the baseline window measured FORWARD from
// each concept's own first correction ($2 seconds wide), so it is
// always at least 1. corrections_after counts everything at or after
// $3, the start of the recent window. Whether those two windows overlap
// — and therefore whether comparing them means anything at all — is
// decided in Go, not here.
func (q *Queries) ConceptCorrectionOutcomes(ctx context.Context, arg ConceptCorrectionOutcomesParams) ([]ConceptCorrectionOutcomesRow, error) {
	rows, err := q.db.Query(ctx, conceptCorrectionOutcomes, arg.IdentityID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConceptCorrectionOutcomesRow
	for rows.Next() {
		var i ConceptCorrectionOutcomesRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.FirstCorrectedAt,
			&i.LastCorrectedAt,
			&i.TotalCorrections,
			&i.CorrectionsBefore,
			&i.CorrectionsAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const conceptIndependentSolves = `-- name: ConceptIndependentSolves :many
SELECT s.slug::text AS slug, COUNT(*)::int AS solves
FROM learning_events le
CROSS JOIN LATERAL jsonb_array_elements_text(le.evidence -> 'concepts') AS s(slug)
WHERE le.identity_id = $1
  AND le.type = 'correction.retried'
  AND jsonb_typeof(le.evidence -> 'concepts') = 'array'
  AND le.evidence ->> 'independent' = 'true'
GROUP BY s.slug
ORDER BY s.slug
`

type ConceptIndependentSolvesRow struct {
	Slug   string
	Solves int32
}

// Per-concept count of correction.retried learning events that were
// INDEPENDENT — the learner recalled the right form without ever
// revealing the answer (application/feedback.Service.RetryCorrection
// sets independent=true only when the retry was both correct and
// unrevealed; see domain/correction.IsGated for why a revealed answer
// must never count as recall).
//
// The concept slugs are threaded through the event's own Evidence
// "concepts" array by RetryCorrection rather than re-joined from
// correction_concepts here, because that array is what the retry
// actually acted on. jsonb_typeof guards events written before that
// array existed (and any future producer that omits it) — without it,
// jsonb_array_elements_text would error on a non-array.
func (q *Queries) ConceptIndependentSolves(ctx context.Context, identityID string) ([]ConceptIndependentSolvesRow, error) {
	rows, err := q.db.Query(ctx, conceptIndependentSolves, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConceptIndependentSolvesRow
	for rows.Next() {
		var i ConceptIndependentSolvesRow
		if err := rows.Scan(&i.Slug, &i.Solves); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const conceptProducedCorrectly = `-- name: ConceptProducedCorrectly :many
SELECT cc.concept_slug AS slug, COUNT(DISTINCT le.id)::int AS produced_correctly
FROM learning_events le
JOIN vocabulary_items vi ON vi.identity_id = le.identity_id AND vi.expression = le.subject
JOIN feedback_requests f ON f.identity_id = le.identity_id
JOIN corrections c ON c.feedback_request_id = f.id
                  AND position(vi.expression IN c.replacement) > 0
JOIN correction_concepts cc ON cc.correction_id = c.id AND cc.resolved
WHERE le.identity_id = $1
  AND le.type = 'vocabulary.produced-correctly'
  AND le.occurred_at >= c.created_at
GROUP BY cc.concept_slug
ORDER BY cc.concept_slug
`

type ConceptProducedCorrectlyRow struct {
	Slug              string
	ProducedCorrectly int32
}

// Per-concept count of DISTINCT vocabulary.produced-correctly events
// for expressions linked to that concept — the strongest "the
// correction worked" signal the schema can express: after being
// corrected on a concept, the learner later used a word from the
// corrected form, unprompted, and no correction touched it (see
// application/vocabulary.Service.DetectProduction for exactly when that
// event fires).
//
// "Linked" has to be a text containment test: nothing in the schema
// joins vocabulary_items to grammar_concepts, so the only available
// link is that the expression occurs inside the REPLACEMENT text of one
// of this identity's corrections tagged with the concept. That is a
// deliberately conservative link — it can miss (the corrected form
// rephrased the word away) but it cannot invent one, since the
// expression must literally appear in text this identity was shown.
//
// COUNT(DISTINCT le.id), not COUNT(*): one production event can match
// several corrections carrying the same concept, and each of those is
// the same single act of production, counted once.
//
// The containment join has no index to use and is O(corrections ×
// expressions) for one identity. That is acceptable at this deployment's
// scale (a single learner's own corpus) and nowhere near a hot path —
// it runs once per /outcomes page load.
func (q *Queries) ConceptProducedCorrectly(ctx context.Context, identityID string) ([]ConceptProducedCorrectlyRow, error) {
	rows, err := q.db.Query(ctx, conceptProducedCorrectly, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConceptProducedCorrectlyRow
	for rows.Next() {
		var i ConceptProducedCorrectlyRow
		if err := rows.Scan(&i.Slug, &i.ProducedCorrectly); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weeklyAssistanceRate = `-- name: WeeklyAssistanceRate :many
SELECT date_trunc('week', f.created_at AT TIME ZONE 'UTC')::date AS week_start,
       COALESCE(SUM(char_length(f.selection_text)), 0)::int AS runes,
       COALESCE(SUM(n.corrections), 0)::int AS corrections
FROM feedback_requests f
LEFT JOIN LATERAL (
    SELECT COUNT(*)::int AS corrections
    FROM corrections c
    WHERE c.feedback_request_id = f.id
) n ON true
WHERE f.identity_id = $1
  AND f.created_at >= $2
GROUP BY week_start
ORDER BY week_start
`

type WeeklyAssistanceRateParams struct {
	IdentityID string
	CreatedAt  pgtype.Timestamptz
}

type WeeklyAssistanceRateRow struct {
	WeekStart   pgtype.Date
	Runes       int32
	Corrections int32
}

// Weekly "how much help did this much writing need": characters
// SUBMITTED FOR REVIEW that week, and how many corrections those
// submissions produced.
//
// The denominator is feedback_requests.selection_text, not every
// character in every document, because that is the text the corrections
// were actually generated from — it makes the ratio answer "the same
// amount of reviewed writing now needs fewer corrections", which is the
// assistance-fading question. (The home dashboard's lifetime
// Statistics.CorrectionsPer1000 uses whole-document length instead; the
// two are different measures and /outcomes never shows them together.)
//
// The LEFT JOIN LATERAL counts each request's corrections once per
// REQUEST, so summing selection_text lengths in the same GROUP BY
// cannot double-count a request that produced several corrections —
// a plain JOIN to corrections would multiply the character count by the
// correction count.
func (q *Queries) WeeklyAssistanceRate(ctx context.Context, arg WeeklyAssistanceRateParams) ([]WeeklyAssistanceRateRow, error) {
	rows, err := q.db.Query(ctx, weeklyAssistanceRate, arg.IdentityID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeeklyAssistanceRateRow
	for rows.Next() {
		var i WeeklyAssistanceRateRow
		if err := rows.Scan(&i.WeekStart, &i.Runes, &i.Corrections); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weeklyCalibration = `-- name: WeeklyCalibration :many
SELECT date_trunc('week', ea.created_at AT TIME ZONE 'UTC')::date AS week_start,
       COUNT(*)::int AS attempts,
       COALESCE(SUM(ea.confidence), 0)::int AS confidence_total,
       (COUNT(*) FILTER (WHERE ea.correct))::int AS corrects
FROM exercise_attempts ea
JOIN exercises e ON e.id = ea.exercise_id
WHERE e.identity_id = $1
  AND ea.confidence IS NOT NULL
  AND ea.created_at >= $2
GROUP BY week_start
ORDER BY week_start
`

type WeeklyCalibrationParams struct {
	IdentityID string
	CreatedAt  pgtype.Timestamptz
}

type WeeklyCalibrationRow struct {
	WeekStart       pgtype.Date
	Attempts        int32
	ConfidenceTotal int32
	Corrects        int32
}

// Weekly raw sums over confidence-rated exercise attempts from $2
// onwards: how many attempts, the total of their self-reported
// confidence values, and how many were correct. The two ratios
// (mean confidence, correct rate) are derived in
// application/outcomes — same raw-counts-in-SQL split
// analytics_v2.sql's ConfidenceCalibration already uses, and the same
// reason: a week with no rated attempts must be presented as "no data",
// which a ratio computed here could not express.
//
// date_trunc runs against created_at converted to plain UTC rather than
// relying on the session's timezone, so week buckets are deterministic
// regardless of connection settings — the Go caller zero-fills against
// boundaries computed the identical way (see postgres.isoWeekStarts).
func (q *Queries) WeeklyCalibration(ctx context.Context, arg WeeklyCalibrationParams) ([]WeeklyCalibrationRow, error) {
	rows, err := q.db.Query(ctx, weeklyCalibration, arg.IdentityID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeeklyCalibrationRow
	for rows.Next() {
		var i WeeklyCalibrationRow
		if err := rows.Scan(
			&i.WeekStart,
			&i.Attempts,
			&i.ConfidenceTotal,
			&i.Corrects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
