// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: priorities.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePriorities = `-- name: DeletePriorities :exec
DELETE FROM learner_priorities WHERE identity_id = $1
`

func (q *Queries) DeletePriorities(ctx context.Context, identityID string) error {
	_, err := q.db.Exec(ctx, deletePriorities, identityID)
	return err
}

const insertPriority = `-- name: InsertPriority :exec
INSERT INTO learner_priorities (identity_id, subject_type, subject, score, reason, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPriorityParams struct {
	IdentityID  string
	SubjectType string
	Subject     string
	Score       float64
	Reason      string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertPriority(ctx context.Context, arg InsertPriorityParams) error {
	_, err := q.db.Exec(ctx, insertPriority,
		arg.IdentityID,
		arg.SubjectType,
		arg.Subject,
		arg.Score,
		arg.Reason,
		arg.UpdatedAt,
	)
	return err
}

const topPriorities = `-- name: TopPriorities :many
SELECT identity_id, subject_type, subject, score, reason, updated_at
FROM learner_priorities
WHERE identity_id = $1
ORDER BY score DESC
LIMIT $2
`

type TopPrioritiesParams struct {
	IdentityID string
	Limit      int32
}

func (q *Queries) TopPriorities(ctx context.Context, arg TopPrioritiesParams) ([]LearnerPriority, error) {
	rows, err := q.db.Query(ctx, topPriorities, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearnerPriority
	for rows.Next() {
		var i LearnerPriority
		if err := rows.Scan(
			&i.IdentityID,
			&i.SubjectType,
			&i.Subject,
			&i.Score,
			&i.Reason,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
