// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueReadingDelivery = `-- name: ClaimDueReadingDelivery :one
UPDATE reading_deliveries SET status = 'sending', claimed_at = $1::timestamptz, attempts = attempts + 1
WHERE id = (
    SELECT c.id FROM reading_deliveries c
    WHERE (c.status = 'pending' AND c.next_attempt_at <= $1::timestamptz)
       OR (c.status = 'sending' AND c.claimed_at < $2::timestamptz)
    ORDER BY c.next_attempt_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, edition_id, identity_id, destination, status, attempts, last_error, created_at, sent_at, claimed_at
`

type ClaimDueReadingDeliveryParams struct {
	Now         pgtype.Timestamptz
	StaleBefore pgtype.Timestamptz
}

type ClaimDueReadingDeliveryRow struct {
	ID          pgtype.UUID
	EditionID   pgtype.UUID
	IdentityID  string
	Destination string
	Status      string
	Attempts    int32
	LastError   string
	CreatedAt   pgtype.Timestamptz
	SentAt      pgtype.Timestamptz
	ClaimedAt   pgtype.Timestamptz
}

// Same claim shape as ClaimDueReadingEdition.
func (q *Queries) ClaimDueReadingDelivery(ctx context.Context, arg ClaimDueReadingDeliveryParams) (ClaimDueReadingDeliveryRow, error) {
	row := q.db.QueryRow(ctx, claimDueReadingDelivery, arg.Now, arg.StaleBefore)
	var i ClaimDueReadingDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.IdentityID,
		&i.Destination,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
		&i.ClaimedAt,
	)
	return i, err
}

const claimDueReadingEdition = `-- name: ClaimDueReadingEdition :one
UPDATE reading_editions SET status = 'analysing', claimed_at = $1::timestamptz, attempts = attempts + 1, updated_at = $1::timestamptz
WHERE id = (
    SELECT c.id FROM reading_editions c
    WHERE (c.status = 'pending' AND c.next_attempt_at <= $1::timestamptz)
       OR (c.status = 'analysing' AND c.claimed_at < $2::timestamptz)
    ORDER BY c.next_attempt_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, article_id, identity_id, status, prompt_name, prompt_version, schema_name, lesson, ai_request_id, attempts, last_error, deliver_when_ready, created_at, updated_at, claimed_at
`

type ClaimDueReadingEditionParams struct {
	Now         pgtype.Timestamptz
	StaleBefore pgtype.Timestamptz
}

type ClaimDueReadingEditionRow struct {
	ID               pgtype.UUID
	ArticleID        pgtype.UUID
	IdentityID       string
	Status           string
	PromptName       string
	PromptVersion    string
	SchemaName       string
	Lesson           []byte
	AiRequestID      string
	Attempts         int32
	LastError        string
	DeliverWhenReady bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ClaimedAt        pgtype.Timestamptz
}

// The analysis worker's claim: the oldest edition that is due (pending
// and past its backoff) or stuck (claimed by a worker that died more
// than a stale interval ago), flipped to analysing and counted as an
// attempt in the same statement. FOR UPDATE SKIP LOCKED lets several
// app replicas run workers without ever claiming the same row.
func (q *Queries) ClaimDueReadingEdition(ctx context.Context, arg ClaimDueReadingEditionParams) (ClaimDueReadingEditionRow, error) {
	row := q.db.QueryRow(ctx, claimDueReadingEdition, arg.Now, arg.StaleBefore)
	var i ClaimDueReadingEditionRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.IdentityID,
		&i.Status,
		&i.PromptName,
		&i.PromptVersion,
		&i.SchemaName,
		&i.Lesson,
		&i.AiRequestID,
		&i.Attempts,
		&i.LastError,
		&i.DeliverWhenReady,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimedAt,
	)
	return i, err
}

const completeReadingEdition = `-- name: CompleteReadingEdition :execrows
UPDATE reading_editions SET status = 'ready', lesson = $2, ai_request_id = $3, last_error = '', claimed_at = NULL, updated_at = $4
WHERE id = $1 AND status = 'analysing' AND claimed_at = $5::timestamptz
`

type CompleteReadingEditionParams struct {
	ID          pgtype.UUID
	Lesson      []byte
	AiRequestID string
	UpdatedAt   pgtype.Timestamptz
	ClaimedAt   pgtype.Timestamptz
}

// Only an edition still in analysing can complete: a stale worker whose
// claim was taken over must not overwrite the newer attempt's outcome.
func (q *Queries) CompleteReadingEdition(ctx context.Context, arg CompleteReadingEditionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeReadingEdition,
		arg.ID,
		arg.Lesson,
		arg.AiRequestID,
		arg.UpdatedAt,
		arg.ClaimedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failReadingDeliveryAttempt = `-- name: FailReadingDeliveryAttempt :execrows
UPDATE reading_deliveries SET
    status = CASE WHEN $4::boolean THEN 'pending' ELSE 'failed' END,
    last_error = $2, next_attempt_at = $3, claimed_at = NULL
WHERE id = $1 AND status = 'sending' AND claimed_at = $5::timestamptz
`

type FailReadingDeliveryAttemptParams struct {
	ID            pgtype.UUID
	LastError     string
	NextAttemptAt pgtype.Timestamptz
	Retry         bool
	ClaimedAt     pgtype.Timestamptz
}

func (q *Queries) FailReadingDeliveryAttempt(ctx context.Context, arg FailReadingDeliveryAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, failReadingDeliveryAttempt,
		arg.ID,
		arg.LastError,
		arg.NextAttemptAt,
		arg.Retry,
		arg.ClaimedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failReadingEditionAttempt = `-- name: FailReadingEditionAttempt :execrows
UPDATE reading_editions SET
    status = CASE WHEN $5::boolean THEN 'pending' ELSE 'failed' END,
    last_error = $2, next_attempt_at = $3, claimed_at = NULL, updated_at = $4
WHERE id = $1 AND status = 'analysing' AND claimed_at = $6::timestamptz
`

type FailReadingEditionAttemptParams struct {
	ID            pgtype.UUID
	LastError     string
	NextAttemptAt pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Retry         bool
	ClaimedAt     pgtype.Timestamptz
}

// A failed attempt goes back to pending with a backoff, or to failed
// when retry is false. Same claim guard as CompleteReadingEdition.
func (q *Queries) FailReadingEditionAttempt(ctx context.Context, arg FailReadingEditionAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, failReadingEditionAttempt,
		arg.ID,
		arg.LastError,
		arg.NextAttemptAt,
		arg.UpdatedAt,
		arg.Retry,
		arg.ClaimedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReadingArticle = `-- name: GetReadingArticle :one
SELECT id, identity_id, source_url, source_name, title, author, published_at, paragraphs, content_hash, created_at
FROM reading_articles
WHERE id = $1 AND identity_id = $2 AND deleted_at IS NULL
`

type GetReadingArticleParams struct {
	ID         pgtype.UUID
	IdentityID string
}

type GetReadingArticleRow struct {
	ID          pgtype.UUID
	IdentityID  string
	SourceUrl   string
	SourceName  string
	Title       string
	Author      string
	PublishedAt pgtype.Timestamptz
	Paragraphs  []byte
	ContentHash string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetReadingArticle(ctx context.Context, arg GetReadingArticleParams) (GetReadingArticleRow, error) {
	row := q.db.QueryRow(ctx, getReadingArticle, arg.ID, arg.IdentityID)
	var i GetReadingArticleRow
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceUrl,
		&i.SourceName,
		&i.Title,
		&i.Author,
		&i.PublishedAt,
		&i.Paragraphs,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getReadingEdition = `-- name: GetReadingEdition :one
SELECT e.id, e.article_id, e.identity_id, e.status, e.prompt_name, e.prompt_version, e.schema_name, e.lesson, e.ai_request_id, e.attempts, e.last_error, e.deliver_when_ready, e.created_at, e.updated_at
FROM reading_editions e
JOIN reading_articles a ON a.id = e.article_id
WHERE e.id = $1 AND e.identity_id = $2 AND a.deleted_at IS NULL
`

type GetReadingEditionParams struct {
	ID         pgtype.UUID
	IdentityID string
}

type GetReadingEditionRow struct {
	ID               pgtype.UUID
	ArticleID        pgtype.UUID
	IdentityID       string
	Status           string
	PromptName       string
	PromptVersion    string
	SchemaName       string
	Lesson           []byte
	AiRequestID      string
	Attempts         int32
	LastError        string
	DeliverWhenReady bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// Identity-scoped, and hidden once its article is soft-deleted: an
// edition is only reachable through an article the learner can see.
func (q *Queries) GetReadingEdition(ctx context.Context, arg GetReadingEditionParams) (GetReadingEditionRow, error) {
	row := q.db.QueryRow(ctx, getReadingEdition, arg.ID, arg.IdentityID)
	var i GetReadingEditionRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.IdentityID,
		&i.Status,
		&i.PromptName,
		&i.PromptVersion,
		&i.SchemaName,
		&i.Lesson,
		&i.AiRequestID,
		&i.Attempts,
		&i.LastError,
		&i.DeliverWhenReady,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReadingFigure = `-- name: GetReadingFigure :one
SELECT f.ordinal, f.after_paragraph, f.caption, f.alt, f.is_lead, f.in_text, f.media_type, f.width, f.height, f.sha256, f.data
FROM reading_article_figures f
JOIN reading_articles a ON a.id = f.article_id
WHERE f.article_id = $1 AND a.identity_id = $2 AND a.deleted_at IS NULL AND f.ordinal = $3
`

type GetReadingFigureParams struct {
	ArticleID  pgtype.UUID
	IdentityID string
	Ordinal    int32
}

type GetReadingFigureRow struct {
	Ordinal        int32
	AfterParagraph int32
	Caption        string
	Alt            string
	IsLead         bool
	InText         bool
	MediaType      string
	Width          int32
	Height         int32
	Sha256         string
	Data           []byte
}

func (q *Queries) GetReadingFigure(ctx context.Context, arg GetReadingFigureParams) (GetReadingFigureRow, error) {
	row := q.db.QueryRow(ctx, getReadingFigure, arg.ArticleID, arg.IdentityID, arg.Ordinal)
	var i GetReadingFigureRow
	err := row.Scan(
		&i.Ordinal,
		&i.AfterParagraph,
		&i.Caption,
		&i.Alt,
		&i.IsLead,
		&i.InText,
		&i.MediaType,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.Data,
	)
	return i, err
}

const inFlightReadingDelivery = `-- name: InFlightReadingDelivery :one
SELECT id, edition_id, identity_id, destination, status, attempts, last_error, created_at, sent_at
FROM reading_deliveries
WHERE edition_id = $1 AND destination = $2 AND status IN ('pending', 'sending')
`

type InFlightReadingDeliveryParams struct {
	EditionID   pgtype.UUID
	Destination string
}

type InFlightReadingDeliveryRow struct {
	ID          pgtype.UUID
	EditionID   pgtype.UUID
	IdentityID  string
	Destination string
	Status      string
	Attempts    int32
	LastError   string
	CreatedAt   pgtype.Timestamptz
	SentAt      pgtype.Timestamptz
}

func (q *Queries) InFlightReadingDelivery(ctx context.Context, arg InFlightReadingDeliveryParams) (InFlightReadingDeliveryRow, error) {
	row := q.db.QueryRow(ctx, inFlightReadingDelivery, arg.EditionID, arg.Destination)
	var i InFlightReadingDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.IdentityID,
		&i.Destination,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const insertReadingDelivery = `-- name: InsertReadingDelivery :one
INSERT INTO reading_deliveries (id, edition_id, identity_id, destination, status, next_attempt_at, created_at)
VALUES ($1, $2, $3, $4, 'pending', $5, $5)
ON CONFLICT (edition_id, destination) WHERE status IN ('pending', 'sending') DO NOTHING
RETURNING id, edition_id, identity_id, destination, status, attempts, last_error, created_at, sent_at
`

type InsertReadingDeliveryParams struct {
	ID            pgtype.UUID
	EditionID     pgtype.UUID
	IdentityID    string
	Destination   string
	NextAttemptAt pgtype.Timestamptz
}

type InsertReadingDeliveryRow struct {
	ID          pgtype.UUID
	EditionID   pgtype.UUID
	IdentityID  string
	Destination string
	Status      string
	Attempts    int32
	LastError   string
	CreatedAt   pgtype.Timestamptz
	SentAt      pgtype.Timestamptz
}

// Queues a delivery unless one for the same edition and destination is
// already in flight (reading_deliveries_inflight_uq), in which case no
// row comes back and the caller reads the in-flight one instead.
func (q *Queries) InsertReadingDelivery(ctx context.Context, arg InsertReadingDeliveryParams) (InsertReadingDeliveryRow, error) {
	row := q.db.QueryRow(ctx, insertReadingDelivery,
		arg.ID,
		arg.EditionID,
		arg.IdentityID,
		arg.Destination,
		arg.NextAttemptAt,
	)
	var i InsertReadingDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.IdentityID,
		&i.Destination,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const insertReadingEdition = `-- name: InsertReadingEdition :exec
INSERT INTO reading_editions (id, article_id, identity_id, status, prompt_name, prompt_version, schema_name, deliver_when_ready, next_attempt_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)
`

type InsertReadingEditionParams struct {
	ID               pgtype.UUID
	ArticleID        pgtype.UUID
	IdentityID       string
	Status           string
	PromptName       string
	PromptVersion    string
	SchemaName       string
	DeliverWhenReady bool
	NextAttemptAt    pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertReadingEdition(ctx context.Context, arg InsertReadingEditionParams) error {
	_, err := q.db.Exec(ctx, insertReadingEdition,
		arg.ID,
		arg.ArticleID,
		arg.IdentityID,
		arg.Status,
		arg.PromptName,
		arg.PromptVersion,
		arg.SchemaName,
		arg.DeliverWhenReady,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	return err
}

const latestReadingEdition = `-- name: LatestReadingEdition :one
SELECT e.id, e.article_id, e.identity_id, e.status, e.prompt_name, e.prompt_version, e.schema_name, e.lesson, e.ai_request_id, e.attempts, e.last_error, e.deliver_when_ready, e.created_at, e.updated_at
FROM reading_editions e
WHERE e.article_id = $1 AND e.identity_id = $2 AND e.prompt_name = $3 AND e.prompt_version = $4
ORDER BY e.created_at DESC
LIMIT 1
`

type LatestReadingEditionParams struct {
	ArticleID     pgtype.UUID
	IdentityID    string
	PromptName    string
	PromptVersion string
}

type LatestReadingEditionRow struct {
	ID               pgtype.UUID
	ArticleID        pgtype.UUID
	IdentityID       string
	Status           string
	PromptName       string
	PromptVersion    string
	SchemaName       string
	Lesson           []byte
	AiRequestID      string
	Attempts         int32
	LastError        string
	DeliverWhenReady bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// The newest edition of an article made with one prompt version — what
// Submit consults to decide whether a repeat submission needs any new
// work at all.
func (q *Queries) LatestReadingEdition(ctx context.Context, arg LatestReadingEditionParams) (LatestReadingEditionRow, error) {
	row := q.db.QueryRow(ctx, latestReadingEdition,
		arg.ArticleID,
		arg.IdentityID,
		arg.PromptName,
		arg.PromptVersion,
	)
	var i LatestReadingEditionRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.IdentityID,
		&i.Status,
		&i.PromptName,
		&i.PromptVersion,
		&i.SchemaName,
		&i.Lesson,
		&i.AiRequestID,
		&i.Attempts,
		&i.LastError,
		&i.DeliverWhenReady,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReadingDeliveries = `-- name: ListReadingDeliveries :many
SELECT id, edition_id, identity_id, destination, status, attempts, last_error, created_at, sent_at
FROM reading_deliveries
WHERE edition_id = $1 AND identity_id = $2
ORDER BY created_at DESC
`

type ListReadingDeliveriesParams struct {
	EditionID  pgtype.UUID
	IdentityID string
}

type ListReadingDeliveriesRow struct {
	ID          pgtype.UUID
	EditionID   pgtype.UUID
	IdentityID  string
	Destination string
	Status      string
	Attempts    int32
	LastError   string
	CreatedAt   pgtype.Timestamptz
	SentAt      pgtype.Timestamptz
}

func (q *Queries) ListReadingDeliveries(ctx context.Context, arg ListReadingDeliveriesParams) ([]ListReadingDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listReadingDeliveries, arg.EditionID, arg.IdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadingDeliveriesRow
	for rows.Next() {
		var i ListReadingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.IdentityID,
			&i.Destination,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingEditions = `-- name: ListReadingEditions :many
SELECT DISTINCT ON (a.id)
    e.id AS edition_id, e.status, e.last_error, e.created_at AS edition_created_at,
    a.id AS article_id, a.title, a.source_name, a.source_url, a.published_at, a.created_at AS article_created_at,
    COALESCE((SELECT d.status FROM reading_deliveries d WHERE d.edition_id = e.id ORDER BY d.created_at DESC LIMIT 1), '')::text AS delivery_status
FROM reading_articles a
JOIN reading_editions e ON e.article_id = a.id
WHERE a.identity_id = $1 AND a.deleted_at IS NULL
ORDER BY a.id, e.created_at DESC
`

type ListReadingEditionsRow struct {
	EditionID        pgtype.UUID
	Status           string
	LastError        string
	EditionCreatedAt pgtype.Timestamptz
	ArticleID        pgtype.UUID
	Title            string
	SourceName       string
	SourceUrl        string
	PublishedAt      pgtype.Timestamptz
	ArticleCreatedAt pgtype.Timestamptz
	DeliveryStatus   string
}

// /reading's list: one row per visible article — its newest edition,
// plus that edition's newest delivery status (empty when never sent).
func (q *Queries) ListReadingEditions(ctx context.Context, identityID string) ([]ListReadingEditionsRow, error) {
	rows, err := q.db.Query(ctx, listReadingEditions, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadingEditionsRow
	for rows.Next() {
		var i ListReadingEditionsRow
		if err := rows.Scan(
			&i.EditionID,
			&i.Status,
			&i.LastError,
			&i.EditionCreatedAt,
			&i.ArticleID,
			&i.Title,
			&i.SourceName,
			&i.SourceUrl,
			&i.PublishedAt,
			&i.ArticleCreatedAt,
			&i.DeliveryStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingFigures = `-- name: ListReadingFigures :many

SELECT f.ordinal, f.after_paragraph, f.caption, f.alt, f.is_lead, f.in_text, f.media_type, f.width, f.height, f.sha256
FROM reading_article_figures f
JOIN reading_articles a ON a.id = f.article_id
WHERE f.article_id = $1 AND a.identity_id = $2 AND a.deleted_at IS NULL
ORDER BY f.ordinal
`

type ListReadingFiguresParams struct {
	ArticleID  pgtype.UUID
	IdentityID string
}

type ListReadingFiguresRow struct {
	Ordinal        int32
	AfterParagraph int32
	Caption        string
	Alt            string
	IsLead         bool
	InText         bool
	MediaType      string
	Width          int32
	Height         int32
	Sha256         string
}

// AttachFigures is not a sqlc query: sqlc cannot type a multi-array
// unnest, so the repository runs that insert through the pool (see
// attachFiguresSQL in adapters/postgres/reading.go).
func (q *Queries) ListReadingFigures(ctx context.Context, arg ListReadingFiguresParams) ([]ListReadingFiguresRow, error) {
	rows, err := q.db.Query(ctx, listReadingFigures, arg.ArticleID, arg.IdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadingFiguresRow
	for rows.Next() {
		var i ListReadingFiguresRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.AfterParagraph,
			&i.Caption,
			&i.Alt,
			&i.IsLead,
			&i.InText,
			&i.MediaType,
			&i.Width,
			&i.Height,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReadingDeliverySent = `-- name: MarkReadingDeliverySent :execrows
UPDATE reading_deliveries SET status = 'sent', sent_at = $2, last_error = '', claimed_at = NULL
WHERE id = $1 AND status = 'sending' AND claimed_at = $3::timestamptz
`

type MarkReadingDeliverySentParams struct {
	ID        pgtype.UUID
	SentAt    pgtype.Timestamptz
	ClaimedAt pgtype.Timestamptz
}

func (q *Queries) MarkReadingDeliverySent(ctx context.Context, arg MarkReadingDeliverySentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markReadingDeliverySent, arg.ID, arg.SentAt, arg.ClaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreReadingArticle = `-- name: RestoreReadingArticle :execrows
UPDATE reading_articles SET deleted_at = NULL
WHERE id = $1 AND identity_id = $2
`

type RestoreReadingArticleParams struct {
	ID         pgtype.UUID
	IdentityID string
}

func (q *Queries) RestoreReadingArticle(ctx context.Context, arg RestoreReadingArticleParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreReadingArticle, arg.ID, arg.IdentityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteReadingArticle = `-- name: SoftDeleteReadingArticle :execrows
UPDATE reading_articles SET deleted_at = COALESCE(deleted_at, $3::timestamptz)
WHERE id = $1 AND identity_id = $2
`

type SoftDeleteReadingArticleParams struct {
	ID         pgtype.UUID
	IdentityID string
	At         pgtype.Timestamptz
}

// Same identity-scoped, idempotent, non-destructive shape as
// SoftDeleteLesson (db/queries/lessons.sql).
func (q *Queries) SoftDeleteReadingArticle(ctx context.Context, arg SoftDeleteReadingArticleParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteReadingArticle, arg.ID, arg.IdentityID, arg.At)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertReadingArticle = `-- name: UpsertReadingArticle :one
INSERT INTO reading_articles (id, identity_id, source_url, source_name, title, author, published_at, paragraphs, content_hash, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (identity_id, content_hash) DO UPDATE SET identity_id = EXCLUDED.identity_id
RETURNING id, identity_id, source_url, source_name, title, author, published_at, paragraphs, content_hash, created_at, (xmax = 0)::boolean AS inserted
`

type UpsertReadingArticleParams struct {
	ID          pgtype.UUID
	IdentityID  string
	SourceUrl   string
	SourceName  string
	Title       string
	Author      string
	PublishedAt pgtype.Timestamptz
	Paragraphs  []byte
	ContentHash string
	CreatedAt   pgtype.Timestamptz
}

type UpsertReadingArticleRow struct {
	ID          pgtype.UUID
	IdentityID  string
	SourceUrl   string
	SourceName  string
	Title       string
	Author      string
	PublishedAt pgtype.Timestamptz
	Paragraphs  []byte
	ContentHash string
	CreatedAt   pgtype.Timestamptz
	Inserted    bool
}

// Idempotent ingestion keyed on (identity_id, content_hash). A repeat
// submission returns the EXISTING live row untouched; the no-op update
// exists only so RETURNING yields it. A soft-deleted match never reaches
// here: the repository purges it first, so re-importing a deleted
// article starts fresh instead of resurrecting the old one. inserted is
// true only for a genuinely new row (xmax = 0 is postgres' marker for
// "this row version was inserted, not updated").
func (q *Queries) UpsertReadingArticle(ctx context.Context, arg UpsertReadingArticleParams) (UpsertReadingArticleRow, error) {
	row := q.db.QueryRow(ctx, upsertReadingArticle,
		arg.ID,
		arg.IdentityID,
		arg.SourceUrl,
		arg.SourceName,
		arg.Title,
		arg.Author,
		arg.PublishedAt,
		arg.Paragraphs,
		arg.ContentHash,
		arg.CreatedAt,
	)
	var i UpsertReadingArticleRow
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceUrl,
		&i.SourceName,
		&i.Title,
		&i.Author,
		&i.PublishedAt,
		&i.Paragraphs,
		&i.ContentHash,
		&i.CreatedAt,
		&i.Inserted,
	)
	return i, err
}
