// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, identity_id, title, purpose, profile, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSessionParams struct {
	ID         pgtype.UUID
	IdentityID string
	Title      string
	Purpose    string
	Profile    []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.IdentityID,
		arg.Title,
		arg.Purpose,
		arg.Profile,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, identity_id, title, purpose, profile, created_at, updated_at
FROM sessions
WHERE id = $1 AND identity_id = $2
`

type GetSessionParams struct {
	ID         pgtype.UUID
	IdentityID string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.IdentityID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Title,
		&i.Purpose,
		&i.Profile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, identity_id, title, purpose, profile, created_at, updated_at
FROM sessions
WHERE identity_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context, identityID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Title,
			&i.Purpose,
			&i.Profile,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
