// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabulary.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVocabularyEventItemByClientID = `-- name: GetVocabularyEventItemByClientID :one
SELECT item_id FROM vocabulary_events
WHERE identity_id = $1 AND client_event_id = $2
`

type GetVocabularyEventItemByClientIDParams struct {
	IdentityID    string
	ClientEventID pgtype.Text
}

func (q *Queries) GetVocabularyEventItemByClientID(ctx context.Context, arg GetVocabularyEventItemByClientIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getVocabularyEventItemByClientID, arg.IdentityID, arg.ClientEventID)
	var item_id pgtype.UUID
	err := row.Scan(&item_id)
	return item_id, err
}

const getVocabularyItem = `-- name: GetVocabularyItem :one
SELECT id, identity_id, expression, reading, meaning, kind, jlpt_level, source,
       lookups, productions, successful_productions, first_seen, last_event,
       meaning_en, tags
FROM vocabulary_items
WHERE id = $1
`

func (q *Queries) GetVocabularyItem(ctx context.Context, id pgtype.UUID) (VocabularyItem, error) {
	row := q.db.QueryRow(ctx, getVocabularyItem, id)
	var i VocabularyItem
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Expression,
		&i.Reading,
		&i.Meaning,
		&i.Kind,
		&i.JlptLevel,
		&i.Source,
		&i.Lookups,
		&i.Productions,
		&i.SuccessfulProductions,
		&i.FirstSeen,
		&i.LastEvent,
		&i.MeaningEn,
		&i.Tags,
	)
	return i, err
}

const insertVocabularyEvent = `-- name: InsertVocabularyEvent :exec
INSERT INTO vocabulary_events (id, identity_id, item_id, type, payload, client_event_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertVocabularyEventParams struct {
	ID            pgtype.UUID
	IdentityID    string
	ItemID        pgtype.UUID
	Type          string
	Payload       []byte
	ClientEventID pgtype.Text
	OccurredAt    pgtype.Timestamptz
}

func (q *Queries) InsertVocabularyEvent(ctx context.Context, arg InsertVocabularyEventParams) error {
	_, err := q.db.Exec(ctx, insertVocabularyEvent,
		arg.ID,
		arg.IdentityID,
		arg.ItemID,
		arg.Type,
		arg.Payload,
		arg.ClientEventID,
		arg.OccurredAt,
	)
	return err
}

const insertVocabularyItemIfAbsent = `-- name: InsertVocabularyItemIfAbsent :exec
INSERT INTO vocabulary_items
    (id, identity_id, expression, reading, meaning, kind, source, lookups, productions, successful_productions, first_seen, last_event)
VALUES ($1, $2, $3, $4, $5, $6, $7, 0, 0, 0, $8, $8)
ON CONFLICT (identity_id, expression) DO NOTHING
`

type InsertVocabularyItemIfAbsentParams struct {
	ID         pgtype.UUID
	IdentityID string
	Expression string
	Reading    string
	Meaning    string
	Kind       string
	Source     string
	FirstSeen  pgtype.Timestamptz
}

// Task 7's expression-bank seed path: unlike UpsertVocabularyItemOnLookup,
// a conflict on (identity_id, expression) is a silent no-op — an
// existing item's lookups/productions/reading/etc. are never touched.
// This is what makes `jlp seed` re-runnable without resetting a
// learner's real usage of a bank expression back to zero.
func (q *Queries) InsertVocabularyItemIfAbsent(ctx context.Context, arg InsertVocabularyItemIfAbsentParams) error {
	_, err := q.db.Exec(ctx, insertVocabularyItemIfAbsent,
		arg.ID,
		arg.IdentityID,
		arg.Expression,
		arg.Reading,
		arg.Meaning,
		arg.Kind,
		arg.Source,
		arg.FirstSeen,
	)
	return err
}

const listVocabularyActivationCandidates = `-- name: ListVocabularyActivationCandidates :many
SELECT id, identity_id, expression, reading, meaning, kind, jlpt_level, source,
       lookups, productions, successful_productions, first_seen, last_event,
       meaning_en, tags
FROM vocabulary_items
WHERE identity_id = $1
  AND (
        (lookups >= 3 AND productions = 0)
        OR (kind IN ('expression', 'pattern') AND productions = 0)
      )
ORDER BY lookups DESC
LIMIT NULLIF($2::int, 0)
`

type ListVocabularyActivationCandidatesParams struct {
	IdentityID string
	LimitCount int32
}

// PRD §55/§17.5's vocabulary activator, ranked and capped in SQL — the
// same WHERE condition ListVocabularyItems' "activate" branch uses
// above, but with ORDER BY lookups DESC LIMIT pushed down here instead
// of fetched-then-sorted in Go, matching the ORDER BY ... LIMIT $n
// convention TopPriorities already uses for the analogous "top N"
// query over learner_priorities. application/planner.Planner.
// ActivationCandidates is a thin passthrough to this (not to
// ListVocabularyItems), precisely so it stays cheap to call on every
// feedback request even as a learner's vocabulary grows.
// limit_count = 0 means unlimited (NULLIF makes LIMIT NULL, i.e. no
// cap) — see application/planner.Planner.ActivationCandidates' doc
// comment for why limit<=0 is a documented "no cap" affordance.
func (q *Queries) ListVocabularyActivationCandidates(ctx context.Context, arg ListVocabularyActivationCandidatesParams) ([]VocabularyItem, error) {
	rows, err := q.db.Query(ctx, listVocabularyActivationCandidates, arg.IdentityID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VocabularyItem
	for rows.Next() {
		var i VocabularyItem
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Expression,
			&i.Reading,
			&i.Meaning,
			&i.Kind,
			&i.JlptLevel,
			&i.Source,
			&i.Lookups,
			&i.Productions,
			&i.SuccessfulProductions,
			&i.FirstSeen,
			&i.LastEvent,
			&i.MeaningEn,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyExpressions = `-- name: ListVocabularyExpressions :many
SELECT id, expression FROM vocabulary_items WHERE identity_id = $1
`

type ListVocabularyExpressionsRow struct {
	ID         pgtype.UUID
	Expression string
}

func (q *Queries) ListVocabularyExpressions(ctx context.Context, identityID string) ([]ListVocabularyExpressionsRow, error) {
	rows, err := q.db.Query(ctx, listVocabularyExpressions, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabularyExpressionsRow
	for rows.Next() {
		var i ListVocabularyExpressionsRow
		if err := rows.Scan(&i.ID, &i.Expression); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyItems = `-- name: ListVocabularyItems :many
SELECT id, identity_id, expression, reading, meaning, kind, jlpt_level, source,
       lookups, productions, successful_productions, first_seen, last_event,
       meaning_en, tags
FROM vocabulary_items
WHERE identity_id = $1
  AND (
        $2::text = ''
        OR ($2::text = 'looked-up' AND lookups > 0)
        OR ($2::text = 'produced' AND productions > 0)
        OR ($2::text = 'activate' AND (
              (lookups >= 3 AND productions = 0)
              OR (kind IN ('expression', 'pattern') AND productions = 0)
            ))
      )
ORDER BY last_event DESC
`

type ListVocabularyItemsParams struct {
	IdentityID string
	Filter     string
}

func (q *Queries) ListVocabularyItems(ctx context.Context, arg ListVocabularyItemsParams) ([]VocabularyItem, error) {
	rows, err := q.db.Query(ctx, listVocabularyItems, arg.IdentityID, arg.Filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VocabularyItem
	for rows.Next() {
		var i VocabularyItem
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Expression,
			&i.Reading,
			&i.Meaning,
			&i.Kind,
			&i.JlptLevel,
			&i.Source,
			&i.Lookups,
			&i.Productions,
			&i.SuccessfulProductions,
			&i.FirstSeen,
			&i.LastEvent,
			&i.MeaningEn,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordVocabularyProduction = `-- name: RecordVocabularyProduction :exec
UPDATE vocabulary_items SET
    productions            = productions + 1,
    successful_productions = successful_productions + CASE WHEN $1::boolean THEN 1 ELSE 0 END,
    last_event              = $2::timestamptz
WHERE id = $3 AND identity_id = $4
`

type RecordVocabularyProductionParams struct {
	Successful bool
	At         pgtype.Timestamptz
	ID         pgtype.UUID
	IdentityID string
}

func (q *Queries) RecordVocabularyProduction(ctx context.Context, arg RecordVocabularyProductionParams) error {
	_, err := q.db.Exec(ctx, recordVocabularyProduction,
		arg.Successful,
		arg.At,
		arg.ID,
		arg.IdentityID,
	)
	return err
}

const upsertVocabularyItemOnLookup = `-- name: UpsertVocabularyItemOnLookup :one
INSERT INTO vocabulary_items
    (id, identity_id, expression, reading, meaning, kind, source, lookups, productions, successful_productions, first_seen, last_event)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1, 0, 0, $8, $8)
ON CONFLICT (identity_id, expression) DO UPDATE SET
    lookups    = vocabulary_items.lookups + 1,
    last_event = EXCLUDED.last_event,
    reading    = CASE WHEN EXCLUDED.reading <> '' THEN EXCLUDED.reading ELSE vocabulary_items.reading END,
    meaning    = CASE WHEN EXCLUDED.meaning <> '' THEN EXCLUDED.meaning ELSE vocabulary_items.meaning END,
    source     = CASE WHEN EXCLUDED.source  <> '' THEN EXCLUDED.source  ELSE vocabulary_items.source  END
RETURNING id, identity_id, expression, reading, meaning, kind, jlpt_level, source,
          lookups, productions, successful_productions, first_seen, last_event,
          meaning_en, tags
`

type UpsertVocabularyItemOnLookupParams struct {
	ID         pgtype.UUID
	IdentityID string
	Expression string
	Reading    string
	Meaning    string
	Kind       string
	Source     string
	FirstSeen  pgtype.Timestamptz
}

func (q *Queries) UpsertVocabularyItemOnLookup(ctx context.Context, arg UpsertVocabularyItemOnLookupParams) (VocabularyItem, error) {
	row := q.db.QueryRow(ctx, upsertVocabularyItemOnLookup,
		arg.ID,
		arg.IdentityID,
		arg.Expression,
		arg.Reading,
		arg.Meaning,
		arg.Kind,
		arg.Source,
		arg.FirstSeen,
	)
	var i VocabularyItem
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Expression,
		&i.Reading,
		&i.Meaning,
		&i.Kind,
		&i.JlptLevel,
		&i.Source,
		&i.Lookups,
		&i.Productions,
		&i.SuccessfulProductions,
		&i.FirstSeen,
		&i.LastEvent,
		&i.MeaningEn,
		&i.Tags,
	)
	return i, err
}

const upsertVocabularyWord = `-- name: UpsertVocabularyWord :exec
INSERT INTO vocabulary_items
    (id, identity_id, expression, reading, meaning, meaning_en, kind, jlpt_level, source, tags, lookups, productions, successful_productions, first_seen, last_event)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 0, 0, 0, $11, $11)
ON CONFLICT (identity_id, expression) DO UPDATE SET
    reading    = CASE WHEN EXCLUDED.reading    <> '' THEN EXCLUDED.reading    ELSE vocabulary_items.reading    END,
    meaning    = CASE WHEN EXCLUDED.meaning    <> '' THEN EXCLUDED.meaning    ELSE vocabulary_items.meaning    END,
    meaning_en = CASE WHEN EXCLUDED.meaning_en <> '' THEN EXCLUDED.meaning_en ELSE vocabulary_items.meaning_en END,
    jlpt_level = CASE WHEN EXCLUDED.jlpt_level <> 0  THEN EXCLUDED.jlpt_level ELSE vocabulary_items.jlpt_level END,
    source     = CASE WHEN EXCLUDED.source     <> '' THEN EXCLUDED.source     ELSE vocabulary_items.source     END,
    tags       = CASE WHEN jsonb_array_length(EXCLUDED.tags) > 0 THEN EXCLUDED.tags ELSE vocabulary_items.tags END,
    last_event = EXCLUDED.last_event
`

type UpsertVocabularyWordParams struct {
	ID         pgtype.UUID
	IdentityID string
	Expression string
	Reading    string
	Meaning    string
	MeaningEn  string
	Kind       string
	JlptLevel  int32
	Source     string
	Tags       []byte
	FirstSeen  pgtype.Timestamptz
}

// Phase 3 Task 8's bulk sync path (POST /api/v1/words): unlike
// UpsertVocabularyItemOnLookup above, lookups/productions/
// successful_productions are NEVER touched by this — a sync is not a
// lookup event, so they stay at their existing value (0 on first
// insert). Every string field does a sparse merge (empty incoming
// value keeps the existing one; jlpt_level 0 keeps the existing
// level) EXCEPT tags, which replaces wholesale when the incoming
// array is non-empty rather than merging entry-by-entry.
func (q *Queries) UpsertVocabularyWord(ctx context.Context, arg UpsertVocabularyWordParams) error {
	_, err := q.db.Exec(ctx, upsertVocabularyWord,
		arg.ID,
		arg.IdentityID,
		arg.Expression,
		arg.Reading,
		arg.Meaning,
		arg.MeaningEn,
		arg.Kind,
		arg.JlptLevel,
		arg.Source,
		arg.Tags,
		arg.FirstSeen,
	)
	return err
}
