// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabulary.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVocabularyEventItemByClientID = `-- name: GetVocabularyEventItemByClientID :one
SELECT item_id FROM vocabulary_events
WHERE identity_id = $1 AND client_event_id = $2
`

type GetVocabularyEventItemByClientIDParams struct {
	IdentityID    string
	ClientEventID pgtype.Text
}

func (q *Queries) GetVocabularyEventItemByClientID(ctx context.Context, arg GetVocabularyEventItemByClientIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getVocabularyEventItemByClientID, arg.IdentityID, arg.ClientEventID)
	var item_id pgtype.UUID
	err := row.Scan(&item_id)
	return item_id, err
}

const getVocabularyItem = `-- name: GetVocabularyItem :one
SELECT id, identity_id, expression, reading, meaning, kind, jlpt_level, source,
       lookups, productions, successful_productions, first_seen, last_event,
       meaning_en, tags, deleted_at
FROM vocabulary_items
WHERE id = $1
`

// DELIBERATELY sees soft-deleted rows, and is the only vocabulary read
// that does. Its single caller is the client_event_id replay branch
// inside postgres/vocabulary.go's UpsertOnLookup: the item id comes
// from the vocabulary_events row this exact client event already wrote,
// and the contract is "a retried POST returns what the first one
// returned, unchanged". Filtering here would turn a replayed lookup of
// a since-deleted word into an error instead of the same idempotent
// response. Nothing renders this row to a learner — Ingest's own return
// value goes back to the API caller that just retried.
func (q *Queries) GetVocabularyItem(ctx context.Context, id pgtype.UUID) (VocabularyItem, error) {
	row := q.db.QueryRow(ctx, getVocabularyItem, id)
	var i VocabularyItem
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Expression,
		&i.Reading,
		&i.Meaning,
		&i.Kind,
		&i.JlptLevel,
		&i.Source,
		&i.Lookups,
		&i.Productions,
		&i.SuccessfulProductions,
		&i.FirstSeen,
		&i.LastEvent,
		&i.MeaningEn,
		&i.Tags,
		&i.DeletedAt,
	)
	return i, err
}

const getVocabularyItemsByExpressions = `-- name: GetVocabularyItemsByExpressions :many
SELECT id, identity_id, expression, reading, meaning, kind, jlpt_level, source,
       lookups, productions, successful_productions, first_seen, last_event,
       meaning_en, tags, deleted_at
FROM vocabulary_items
WHERE identity_id = $1 AND deleted_at IS NULL AND expression = ANY($2::text[])
`

type GetVocabularyItemsByExpressionsParams struct {
	IdentityID  string
	Expressions []string
}

// Bounded lookup for a SMALL, caller-supplied set of expressions —
// application/feedback.Service.dueExpressionItems' resolve-a-due-
// subject-back-to-Reading/Meaning step (PRD §54): unlike
// ListVocabularyItems (filter=""), which scans the identity's ENTIRE
// vocabulary, this is indexed on (identity_id, expression) and returns
// at most len(expressions) rows — the same "push the bound into SQL"
// principle ListVocabularyActivationCandidates documents above, so
// resolving a handful of due expressions stays cheap regardless of how
// large a learner's vocabulary grows.
func (q *Queries) GetVocabularyItemsByExpressions(ctx context.Context, arg GetVocabularyItemsByExpressionsParams) ([]VocabularyItem, error) {
	rows, err := q.db.Query(ctx, getVocabularyItemsByExpressions, arg.IdentityID, arg.Expressions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VocabularyItem
	for rows.Next() {
		var i VocabularyItem
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Expression,
			&i.Reading,
			&i.Meaning,
			&i.Kind,
			&i.JlptLevel,
			&i.Source,
			&i.Lookups,
			&i.Productions,
			&i.SuccessfulProductions,
			&i.FirstSeen,
			&i.LastEvent,
			&i.MeaningEn,
			&i.Tags,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVocabularyEvent = `-- name: InsertVocabularyEvent :exec
INSERT INTO vocabulary_events (id, identity_id, item_id, type, payload, client_event_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertVocabularyEventParams struct {
	ID            pgtype.UUID
	IdentityID    string
	ItemID        pgtype.UUID
	Type          string
	Payload       []byte
	ClientEventID pgtype.Text
	OccurredAt    pgtype.Timestamptz
}

func (q *Queries) InsertVocabularyEvent(ctx context.Context, arg InsertVocabularyEventParams) error {
	_, err := q.db.Exec(ctx, insertVocabularyEvent,
		arg.ID,
		arg.IdentityID,
		arg.ItemID,
		arg.Type,
		arg.Payload,
		arg.ClientEventID,
		arg.OccurredAt,
	)
	return err
}

const insertVocabularyItemIfAbsent = `-- name: InsertVocabularyItemIfAbsent :exec
INSERT INTO vocabulary_items
    (id, identity_id, expression, reading, meaning, kind, source, lookups, productions, successful_productions, first_seen, last_event)
VALUES ($1, $2, $3, $4, $5, $6, $7, 0, 0, 0, $8, $8)
ON CONFLICT (identity_id, expression) DO NOTHING
`

type InsertVocabularyItemIfAbsentParams struct {
	ID         pgtype.UUID
	IdentityID string
	Expression string
	Reading    string
	Meaning    string
	Kind       string
	Source     string
	FirstSeen  pgtype.Timestamptz
}

// Task 7's expression-bank seed path: unlike UpsertVocabularyItemOnLookup,
// a conflict on (identity_id, expression) is a silent no-op — an
// existing item's lookups/productions/reading/etc. are never touched.
// This is what makes `jlp seed` re-runnable without resetting a
// learner's real usage of a bank expression back to zero.
func (q *Queries) InsertVocabularyItemIfAbsent(ctx context.Context, arg InsertVocabularyItemIfAbsentParams) error {
	_, err := q.db.Exec(ctx, insertVocabularyItemIfAbsent,
		arg.ID,
		arg.IdentityID,
		arg.Expression,
		arg.Reading,
		arg.Meaning,
		arg.Kind,
		arg.Source,
		arg.FirstSeen,
	)
	return err
}

const listVocabularyActivationCandidates = `-- name: ListVocabularyActivationCandidates :many
SELECT id, identity_id, expression, reading, meaning, kind, jlpt_level, source,
       lookups, productions, successful_productions, first_seen, last_event,
       meaning_en, tags, deleted_at
FROM vocabulary_items
WHERE identity_id = $1
  AND deleted_at IS NULL
  AND (
        (lookups >= 3 AND productions = 0)
        OR (kind IN ('expression', 'pattern') AND productions = 0)
      )
ORDER BY lookups DESC
LIMIT NULLIF($2::int, 0)
`

type ListVocabularyActivationCandidatesParams struct {
	IdentityID string
	LimitCount int32
}

// PRD §55/§17.5's vocabulary activator, ranked and capped in SQL — the
// same WHERE condition ListVocabularyItems' "activate" branch uses
// above, but with ORDER BY lookups DESC LIMIT pushed down here instead
// of fetched-then-sorted in Go, matching the ORDER BY ... LIMIT $n
// convention TopPriorities already uses for the analogous "top N"
// query over learner_priorities. application/planner.Planner.
// ActivationCandidates is a thin passthrough to this (not to
// ListVocabularyItems), precisely so it stays cheap to call on every
// feedback request even as a learner's vocabulary grows.
// limit_count = 0 means unlimited (NULLIF makes LIMIT NULL, i.e. no
// cap) — see application/planner.Planner.ActivationCandidates' doc
// comment for why limit<=0 is a documented "no cap" affordance.
func (q *Queries) ListVocabularyActivationCandidates(ctx context.Context, arg ListVocabularyActivationCandidatesParams) ([]VocabularyItem, error) {
	rows, err := q.db.Query(ctx, listVocabularyActivationCandidates, arg.IdentityID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VocabularyItem
	for rows.Next() {
		var i VocabularyItem
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Expression,
			&i.Reading,
			&i.Meaning,
			&i.Kind,
			&i.JlptLevel,
			&i.Source,
			&i.Lookups,
			&i.Productions,
			&i.SuccessfulProductions,
			&i.FirstSeen,
			&i.LastEvent,
			&i.MeaningEn,
			&i.Tags,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyExpressions = `-- name: ListVocabularyExpressions :many
SELECT id, expression FROM vocabulary_items WHERE identity_id = $1 AND deleted_at IS NULL
`

type ListVocabularyExpressionsRow struct {
	ID         pgtype.UUID
	Expression string
}

// The candidate set application/vocabulary.Service.DetectProduction
// scans reviewed text against. The deleted_at filter is not cosmetic
// here: a deleted word left in this set would keep collecting
// vocabulary.produced / vocabulary.produced-correctly events and keep
// re-scheduling itself in retrieval_items, so a word the learner
// removed would go on generating work for them from a row they cannot
// see.
func (q *Queries) ListVocabularyExpressions(ctx context.Context, identityID string) ([]ListVocabularyExpressionsRow, error) {
	rows, err := q.db.Query(ctx, listVocabularyExpressions, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabularyExpressionsRow
	for rows.Next() {
		var i ListVocabularyExpressionsRow
		if err := rows.Scan(&i.ID, &i.Expression); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyItems = `-- name: ListVocabularyItems :many
SELECT id, identity_id, expression, reading, meaning, kind, jlpt_level, source,
       lookups, productions, successful_productions, first_seen, last_event,
       meaning_en, tags, deleted_at
FROM vocabulary_items
WHERE identity_id = $1
  AND deleted_at IS NULL
  AND (
        $2::text = ''
        OR ($2::text = 'looked-up' AND lookups > 0)
        OR ($2::text = 'produced' AND productions > 0)
        OR ($2::text = 'activate' AND (
              (lookups >= 3 AND productions = 0)
              OR (kind IN ('expression', 'pattern') AND productions = 0)
            ))
      )
ORDER BY last_event DESC
`

type ListVocabularyItemsParams struct {
	IdentityID string
	Filter     string
}

func (q *Queries) ListVocabularyItems(ctx context.Context, arg ListVocabularyItemsParams) ([]VocabularyItem, error) {
	rows, err := q.db.Query(ctx, listVocabularyItems, arg.IdentityID, arg.Filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VocabularyItem
	for rows.Next() {
		var i VocabularyItem
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Expression,
			&i.Reading,
			&i.Meaning,
			&i.Kind,
			&i.JlptLevel,
			&i.Source,
			&i.Lookups,
			&i.Productions,
			&i.SuccessfulProductions,
			&i.FirstSeen,
			&i.LastEvent,
			&i.MeaningEn,
			&i.Tags,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordVocabularyProduction = `-- name: RecordVocabularyProduction :exec
UPDATE vocabulary_items SET
    productions            = productions + 1,
    successful_productions = successful_productions + CASE WHEN $1::boolean THEN 1 ELSE 0 END,
    last_event              = $2::timestamptz
WHERE id = $3 AND identity_id = $4 AND deleted_at IS NULL
`

type RecordVocabularyProductionParams struct {
	Successful bool
	At         pgtype.Timestamptz
	ID         pgtype.UUID
	IdentityID string
}

func (q *Queries) RecordVocabularyProduction(ctx context.Context, arg RecordVocabularyProductionParams) error {
	_, err := q.db.Exec(ctx, recordVocabularyProduction,
		arg.Successful,
		arg.At,
		arg.ID,
		arg.IdentityID,
	)
	return err
}

const restoreVocabularyItem = `-- name: RestoreVocabularyItem :execrows
UPDATE vocabulary_items SET deleted_at = NULL
WHERE id = $1 AND identity_id = $2
`

type RestoreVocabularyItemParams struct {
	ID         pgtype.UUID
	IdentityID string
}

// The way back — see SoftDeleteSession/RestoreSession in
// db/queries/sessions.sql.
func (q *Queries) RestoreVocabularyItem(ctx context.Context, arg RestoreVocabularyItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreVocabularyItem, arg.ID, arg.IdentityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteVocabularyItem = `-- name: SoftDeleteVocabularyItem :execrows

UPDATE vocabulary_items SET deleted_at = COALESCE(deleted_at, $3::timestamptz)
WHERE id = $1 AND identity_id = $2
`

type SoftDeleteVocabularyItemParams struct {
	ID         pgtype.UUID
	IdentityID string
	At         pgtype.Timestamptz
}

// deleted_at is deliberately absent from that SET list. A bulk deck
// sync must never undo a delete: if it did, a word the learner removed
// would return on the very next sync and could never be got rid of.
// Only UpsertVocabularyItemOnLookup — one expression, looked up by the
// learner on purpose, right now — clears deleted_at. See its comment.
// The learner's "delete this word" (Phase 4 Task D). Identity-scoped,
// idempotent, and non-destructive for exactly the reasons
// db/queries/sessions.sql's SoftDeleteSession spells out — read that
// comment; this is the same statement over a different table, on
// purpose, so there is one shape to understand rather than three.
//
// The vocabulary_events rows behind the item are untouched, as are the
// learning_events its lookups and productions produced: /learner's
// vocabulary funnel and /outcomes are computed from those and must not
// move when a learner tidies their word list.
func (q *Queries) SoftDeleteVocabularyItem(ctx context.Context, arg SoftDeleteVocabularyItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteVocabularyItem, arg.ID, arg.IdentityID, arg.At)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertVocabularyItemOnLookup = `-- name: UpsertVocabularyItemOnLookup :one
INSERT INTO vocabulary_items
    (id, identity_id, expression, reading, meaning, kind, source, lookups, productions, successful_productions, first_seen, last_event)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1, 0, 0, $8, $8)
ON CONFLICT (identity_id, expression) DO UPDATE SET
    lookups    = vocabulary_items.lookups + 1,
    last_event = EXCLUDED.last_event,
    reading    = CASE WHEN EXCLUDED.reading <> '' THEN EXCLUDED.reading ELSE vocabulary_items.reading END,
    meaning    = CASE WHEN EXCLUDED.meaning <> '' THEN EXCLUDED.meaning ELSE vocabulary_items.meaning END,
    source     = CASE WHEN EXCLUDED.source  <> '' THEN EXCLUDED.source  ELSE vocabulary_items.source  END,
    -- Soft delete (Phase 4 Task D): a fresh lookup RESURRECTS a
    -- deleted word. UNIQUE (identity_id, expression) means the
    -- conflict lands on the deleted row, so the only alternative is
    -- leaving deleted_at set — and then a learner who looks the word
    -- up again in the browser extension sees their lookup vanish into
    -- a row they cannot reach, with no way to tell why. A word coming
    -- back after you deliberately looked it up again is visible and
    -- undoable; a lookup silently going nowhere is neither.
    --
    -- This applies ONLY to this query — one expression at a time.
    -- UpsertVocabularyWord below (the bulk deck sync) and
    -- InsertVocabularyItemIfAbsent (the expression-bank seed) both
    -- leave deleted_at alone, because a delete must survive the next
    -- automatic sync — otherwise deleting a synced word would be
    -- permanently impossible.
    --
    -- Be precise about who "the learner" is here: resurrect is a
    -- property of THIS QUERY, not of any particular caller, and it has
    -- two — POST /api/v1/vocabulary/events and the MQTT bridge, whose
    -- identity comes from the topic (learner/{id}/vocabulary/ingest)
    -- with no per-message auth. So a broker publisher, including a
    -- retained message replayed on reconnect, can undo a word delete.
    -- That is a consequence of the MQTT channel's existing trust model,
    -- not something resurrect introduces: the same publisher can
    -- already CREATE vocabulary for that identity, which is strictly
    -- more than bringing one back. Worth knowing before that channel is
    -- exposed beyond a trusted LAN broker.
    deleted_at = NULL
RETURNING id, identity_id, expression, reading, meaning, kind, jlpt_level, source,
          lookups, productions, successful_productions, first_seen, last_event,
          meaning_en, tags, deleted_at
`

type UpsertVocabularyItemOnLookupParams struct {
	ID         pgtype.UUID
	IdentityID string
	Expression string
	Reading    string
	Meaning    string
	Kind       string
	Source     string
	FirstSeen  pgtype.Timestamptz
}

func (q *Queries) UpsertVocabularyItemOnLookup(ctx context.Context, arg UpsertVocabularyItemOnLookupParams) (VocabularyItem, error) {
	row := q.db.QueryRow(ctx, upsertVocabularyItemOnLookup,
		arg.ID,
		arg.IdentityID,
		arg.Expression,
		arg.Reading,
		arg.Meaning,
		arg.Kind,
		arg.Source,
		arg.FirstSeen,
	)
	var i VocabularyItem
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Expression,
		&i.Reading,
		&i.Meaning,
		&i.Kind,
		&i.JlptLevel,
		&i.Source,
		&i.Lookups,
		&i.Productions,
		&i.SuccessfulProductions,
		&i.FirstSeen,
		&i.LastEvent,
		&i.MeaningEn,
		&i.Tags,
		&i.DeletedAt,
	)
	return i, err
}

const upsertVocabularyWord = `-- name: UpsertVocabularyWord :exec
INSERT INTO vocabulary_items
    (id, identity_id, expression, reading, meaning, meaning_en, kind, jlpt_level, source, tags, lookups, productions, successful_productions, first_seen, last_event)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 0, 0, 0, $11, $11)
ON CONFLICT (identity_id, expression) DO UPDATE SET
    reading    = CASE WHEN EXCLUDED.reading    <> '' THEN EXCLUDED.reading    ELSE vocabulary_items.reading    END,
    meaning    = CASE WHEN EXCLUDED.meaning    <> '' THEN EXCLUDED.meaning    ELSE vocabulary_items.meaning    END,
    meaning_en = CASE WHEN EXCLUDED.meaning_en <> '' THEN EXCLUDED.meaning_en ELSE vocabulary_items.meaning_en END,
    jlpt_level = CASE WHEN EXCLUDED.jlpt_level <> 0  THEN EXCLUDED.jlpt_level ELSE vocabulary_items.jlpt_level END,
    source     = CASE WHEN EXCLUDED.source     <> '' THEN EXCLUDED.source     ELSE vocabulary_items.source     END,
    tags       = CASE WHEN jsonb_array_length(EXCLUDED.tags) > 0 THEN EXCLUDED.tags ELSE vocabulary_items.tags END,
    last_event = EXCLUDED.last_event
`

type UpsertVocabularyWordParams struct {
	ID         pgtype.UUID
	IdentityID string
	Expression string
	Reading    string
	Meaning    string
	MeaningEn  string
	Kind       string
	JlptLevel  int32
	Source     string
	Tags       []byte
	FirstSeen  pgtype.Timestamptz
}

// Phase 3 Task 8's bulk sync path (POST /api/v1/words): unlike
// UpsertVocabularyItemOnLookup above, lookups/productions/
// successful_productions are NEVER touched by this — a sync is not a
// lookup event, so they stay at their existing value (0 on first
// insert). Every string field does a sparse merge (empty incoming
// value keeps the existing one; jlpt_level 0 keeps the existing
// level) EXCEPT tags, which replaces wholesale when the incoming
// array is non-empty rather than merging entry-by-entry.
func (q *Queries) UpsertVocabularyWord(ctx context.Context, arg UpsertVocabularyWordParams) error {
	_, err := q.db.Exec(ctx, upsertVocabularyWord,
		arg.ID,
		arg.IdentityID,
		arg.Expression,
		arg.Reading,
		arg.Meaning,
		arg.MeaningEn,
		arg.Kind,
		arg.JlptLevel,
		arg.Source,
		arg.Tags,
		arg.FirstSeen,
	)
	return err
}
